package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountLegalCaseHearing generated by hbm2java
 */
@Entity
@Table(name = "account_legal_case_hearing")
public class AccountLegalCaseHearing implements java.io.Serializable {

	private Integer id;
	private Integer legalcaseId;
	private Date hearingDate;
	private String remarks;
	private String stage;

	public AccountLegalCaseHearing() {
	}

	public AccountLegalCaseHearing(Integer legalcaseId, Date hearingDate, String remarks, String stage) {
		this.legalcaseId = legalcaseId;
		this.hearingDate = hearingDate;
		this.remarks = remarks;
		this.stage = stage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "legalcase_id")
	public Integer getLegalcaseId() {
		return this.legalcaseId;
	}

	public void setLegalcaseId(Integer legalcaseId) {
		this.legalcaseId = legalcaseId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hearing_date", length = 19)
	public Date getHearingDate() {
		return this.hearingDate;
	}

	public void setHearingDate(Date hearingDate) {
		this.hearingDate = hearingDate;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "stage")
	public String getStage() {
		return this.stage;
	}

	public void setStage(String stage) {
		this.stage = stage;
	}

}
