package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AccountLegalCase generated by hbm2java
 */
@Entity
@Table(name = "account_legal_case")
public class AccountLegalCase implements java.io.Serializable {

	private Integer id;
	private Integer accountId;
	private String name;
	private String court;
	private String autorisedPerson;
	private String stage;
	private String caseType;
	private String remarks;
	private String caseOn;
	private String fileVerifiedBy;
	private String advocate;
	private String bccsFileNo;

	public AccountLegalCase() {
	}

	public AccountLegalCase(Integer accountId, String name, String court, String autorisedPerson, String stage,
			String caseType, String remarks, String caseOn, String fileVerifiedBy, String advocate, String bccsFileNo) {
		this.accountId = accountId;
		this.name = name;
		this.court = court;
		this.autorisedPerson = autorisedPerson;
		this.stage = stage;
		this.caseType = caseType;
		this.remarks = remarks;
		this.caseOn = caseOn;
		this.fileVerifiedBy = fileVerifiedBy;
		this.advocate = advocate;
		this.bccsFileNo = bccsFileNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account_id")
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "court")
	public String getCourt() {
		return this.court;
	}

	public void setCourt(String court) {
		this.court = court;
	}

	@Column(name = "autorised_person")
	public String getAutorisedPerson() {
		return this.autorisedPerson;
	}

	public void setAutorisedPerson(String autorisedPerson) {
		this.autorisedPerson = autorisedPerson;
	}

	@Column(name = "stage")
	public String getStage() {
		return this.stage;
	}

	public void setStage(String stage) {
		this.stage = stage;
	}

	@Column(name = "case_type")
	public String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "case_on")
	public String getCaseOn() {
		return this.caseOn;
	}

	public void setCaseOn(String caseOn) {
		this.caseOn = caseOn;
	}

	@Column(name = "file_verified_by")
	public String getFileVerifiedBy() {
		return this.fileVerifiedBy;
	}

	public void setFileVerifiedBy(String fileVerifiedBy) {
		this.fileVerifiedBy = fileVerifiedBy;
	}

	@Column(name = "advocate")
	public String getAdvocate() {
		return this.advocate;
	}

	public void setAdvocate(String advocate) {
		this.advocate = advocate;
	}

	@Column(name = "bccs_file_no")
	public String getBccsFileNo() {
		return this.bccsFileNo;
	}

	public void setBccsFileNo(String bccsFileNo) {
		this.bccsFileNo = bccsFileNo;
	}

}
