package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgentTds generated by hbm2java
 */
@Entity
@Table(name = "agent_tds")
public class AgentTds implements java.io.Serializable {

	private Integer id;
	private Accounts accounts;
	private Agents agents;
	private Transactions transactions;
	private Date createdAt;
	private BigDecimal totalCommission;
	private BigDecimal tds;
	private BigDecimal netCommission;

	public AgentTds() {
	}

	public AgentTds(Accounts accounts, Agents agents, Transactions transactions, Date createdAt,
			BigDecimal totalCommission, BigDecimal tds, BigDecimal netCommission) {
		this.accounts = accounts;
		this.agents = agents;
		this.transactions = transactions;
		this.createdAt = createdAt;
		this.totalCommission = totalCommission;
		this.tds = tds;
		this.netCommission = netCommission;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "related_account_id")
	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agent_id")
	public Agents getAgents() {
		return this.agents;
	}

	public void setAgents(Agents agents) {
		this.agents = agents;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transaction_id")
	public Transactions getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Transactions transactions) {
		this.transactions = transactions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "total_commission", precision = 10)
	public BigDecimal getTotalCommission() {
		return this.totalCommission;
	}

	public void setTotalCommission(BigDecimal totalCommission) {
		this.totalCommission = totalCommission;
	}

	@Column(name = "tds", precision = 10)
	public BigDecimal getTds() {
		return this.tds;
	}

	public void setTds(BigDecimal tds) {
		this.tds = tds;
	}

	@Column(name = "net_commission", precision = 10)
	public BigDecimal getNetCommission() {
		return this.netCommission;
	}

	public void setNetCommission(BigDecimal netCommission) {
		this.netCommission = netCommission;
	}

}
