package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

/**
 * BalanceSheet generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "balance_sheet")
public class BalanceSheet implements java.io.Serializable {

	private Integer id;
	private String name;
	private String positiveSide;
	private byte isPandl;
	private String showSub;
	private String subtractFrom;
	private int orderOfBalanceSheet;

	public BalanceSheet() {
	}

	public BalanceSheet(String name, String positiveSide, byte isPandl, String showSub, String subtractFrom,
			int orderOfBalanceSheet) {
		super();
		this.name = name;
		this.positiveSide = positiveSide;
		this.isPandl = isPandl;
		this.showSub = showSub;
		this.subtractFrom = subtractFrom;
		this.orderOfBalanceSheet = orderOfBalanceSheet;
	}

	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "positive_side", nullable = false, length = 2)
	public String getPositiveSide() {
		return positiveSide;
	}

	public void setPositiveSide(String positiveSide) {
		this.positiveSide = positiveSide;
	}

	@Column(name = "is_pandl", nullable = false)
	public byte getIsPandl() {
		return isPandl;
	}

	public void setIsPandl(byte isPandl) {
		this.isPandl = isPandl;
	}

	@Column(name = "show_sub", nullable = false, length = 20)
	public String getShowSub() {
		return showSub;
	}

	public void setShowSub(String showSub) {
		this.showSub = showSub;
	}
	
	@Column(name = "subtract_from", nullable = false, length = 2)
	public String getSubtractFrom() {
		return subtractFrom;
	}

	public void setSubtractFrom(String subtractFrom) {
		this.subtractFrom = subtractFrom;
	}

	
	@Column(name = "order_of_balance_sheet", nullable = false)
	public int getOrderOfBalanceSheet() {
		return orderOfBalanceSheet;
	}

	public void setOrderOfBalanceSheet(int orderOfBalanceSheet) {
		this.orderOfBalanceSheet = orderOfBalanceSheet;
	}




}