package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dealers generated by hbm2java
 */
@Entity
@Table(name = "dealers")
public class Dealers implements java.io.Serializable {

	private Integer id;
	private Dsa dsa;
	private String name;
	private String address;
	private String loanPaneltyPerDay;
	private String timeOverCharge;
	private String dealerMonthlyDate;
	private String properitorName;
	private String properitorPhoneNo1;
	private String properitorPhoneNo2;
	private String emailId1;
	private String emailId2;
	private String product;
	private Byte activeStatus;
	private String username;
	private String password;
	private Set documentsSubmitteds = new HashSet(0);

	public Dealers() {
	}

	public Dealers(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Dealers(Dsa dsa, String name, String address, String loanPaneltyPerDay, String timeOverCharge,
			String dealerMonthlyDate, String properitorName, String properitorPhoneNo1, String properitorPhoneNo2,
			String emailId1, String emailId2, String product, Byte activeStatus, String username, String password,
			Set documentsSubmitteds) {
		this.dsa = dsa;
		this.name = name;
		this.address = address;
		this.loanPaneltyPerDay = loanPaneltyPerDay;
		this.timeOverCharge = timeOverCharge;
		this.dealerMonthlyDate = dealerMonthlyDate;
		this.properitorName = properitorName;
		this.properitorPhoneNo1 = properitorPhoneNo1;
		this.properitorPhoneNo2 = properitorPhoneNo2;
		this.emailId1 = emailId1;
		this.emailId2 = emailId2;
		this.product = product;
		this.activeStatus = activeStatus;
		this.username = username;
		this.password = password;
		this.documentsSubmitteds = documentsSubmitteds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dsa_id")
	public Dsa getDsa() {
		return this.dsa;
	}

	public void setDsa(Dsa dsa) {
		this.dsa = dsa;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Address", length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "loan_panelty_per_day")
	public String getLoanPaneltyPerDay() {
		return this.loanPaneltyPerDay;
	}

	public void setLoanPaneltyPerDay(String loanPaneltyPerDay) {
		this.loanPaneltyPerDay = loanPaneltyPerDay;
	}

	@Column(name = "time_over_charge")
	public String getTimeOverCharge() {
		return this.timeOverCharge;
	}

	public void setTimeOverCharge(String timeOverCharge) {
		this.timeOverCharge = timeOverCharge;
	}

	@Column(name = "dealer_monthly_date")
	public String getDealerMonthlyDate() {
		return this.dealerMonthlyDate;
	}

	public void setDealerMonthlyDate(String dealerMonthlyDate) {
		this.dealerMonthlyDate = dealerMonthlyDate;
	}

	@Column(name = "properitor_name")
	public String getProperitorName() {
		return this.properitorName;
	}

	public void setProperitorName(String properitorName) {
		this.properitorName = properitorName;
	}

	@Column(name = "properitor_phone_no_1")
	public String getProperitorPhoneNo1() {
		return this.properitorPhoneNo1;
	}

	public void setProperitorPhoneNo1(String properitorPhoneNo1) {
		this.properitorPhoneNo1 = properitorPhoneNo1;
	}

	@Column(name = "properitor_phone_no_2")
	public String getProperitorPhoneNo2() {
		return this.properitorPhoneNo2;
	}

	public void setProperitorPhoneNo2(String properitorPhoneNo2) {
		this.properitorPhoneNo2 = properitorPhoneNo2;
	}

	@Column(name = "email_id_1")
	public String getEmailId1() {
		return this.emailId1;
	}

	public void setEmailId1(String emailId1) {
		this.emailId1 = emailId1;
	}

	@Column(name = "email_id_2")
	public String getEmailId2() {
		return this.emailId2;
	}

	public void setEmailId2(String emailId2) {
		this.emailId2 = emailId2;
	}

	@Column(name = "product")
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "ActiveStatus")
	public Byte getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(Byte activeStatus) {
		this.activeStatus = activeStatus;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealers")
	public Set<DocumentsSubmitted> getDocumentsSubmitteds() {
		return this.documentsSubmitteds;
	}

	public void setDocumentsSubmitteds(Set documentsSubmitteds) {
		this.documentsSubmitteds = documentsSubmitteds;
	}

}
