package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DsaGuarantors generated by hbm2java
 */
@Entity
@Table(name = "dsa_guarantors")
public class DsaGuarantors implements java.io.Serializable {

	private Integer id;
	private Dsa dsa;
	private Members members;
	private Set documentsSubmitteds = new HashSet(0);

	public DsaGuarantors() {
	}

	public DsaGuarantors(Dsa dsa, Members members, Set documentsSubmitteds) {
		this.dsa = dsa;
		this.members = members;
		this.documentsSubmitteds = documentsSubmitteds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dsa_id")
	public Dsa getDsa() {
		return this.dsa;
	}

	public void setDsa(Dsa dsa) {
		this.dsa = dsa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Members getMembers() {
		return this.members;
	}

	public void setMembers(Members members) {
		this.members = members;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dsaGuarantors")
	public Set<DocumentsSubmitted> getDocumentsSubmitteds() {
		return this.documentsSubmitteds;
	}

	public void setDocumentsSubmitteds(Set documentsSubmitteds) {
		this.documentsSubmitteds = documentsSubmitteds;
	}

}
