package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeSalaryRecord generated by hbm2java
 */
@Entity
@Table(name = "employee_salary_record")
public class EmployeeSalaryRecord implements java.io.Serializable {

	private Integer id;
	private Branches branches;
	private XbankEmployees xbankEmployees;
	private String month;
	private String year;
	private String totalDays;
	private String paidDays;
	private String leave;
	private String salary;
	private String ded;
	private String pfAmount;
	private String otherAllowance;
	private String incentive;
	private String allowPaid;
	private String netPayable;
	private String narration;
	private String pfSalary;
	private String cl;
	private String ccl;
	private String lwp;
	private String absent;
	private String monthlyOff;
	private String totalMonthDay;

	public EmployeeSalaryRecord() {
	}

	public EmployeeSalaryRecord(String incentive) {
		this.incentive = incentive;
	}

	public EmployeeSalaryRecord(Branches branches, XbankEmployees xbankEmployees, String month, String year,
			String totalDays, String paidDays, String leave, String salary, String ded, String pfAmount,
			String otherAllowance, String incentive, String allowPaid, String netPayable, String narration,
			String pfSalary, String cl, String ccl, String lwp, String absent, String monthlyOff,
			String totalMonthDay) {
		this.branches = branches;
		this.xbankEmployees = xbankEmployees;
		this.month = month;
		this.year = year;
		this.totalDays = totalDays;
		this.paidDays = paidDays;
		this.leave = leave;
		this.salary = salary;
		this.ded = ded;
		this.pfAmount = pfAmount;
		this.otherAllowance = otherAllowance;
		this.incentive = incentive;
		this.allowPaid = allowPaid;
		this.netPayable = netPayable;
		this.narration = narration;
		this.pfSalary = pfSalary;
		this.cl = cl;
		this.ccl = ccl;
		this.lwp = lwp;
		this.absent = absent;
		this.monthlyOff = monthlyOff;
		this.totalMonthDay = totalMonthDay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id")
	public XbankEmployees getXbankEmployees() {
		return this.xbankEmployees;
	}

	public void setXbankEmployees(XbankEmployees xbankEmployees) {
		this.xbankEmployees = xbankEmployees;
	}

	@Column(name = "month")
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "year")
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "total_days")
	public String getTotalDays() {
		return this.totalDays;
	}

	public void setTotalDays(String totalDays) {
		this.totalDays = totalDays;
	}

	@Column(name = "paid_days")
	public String getPaidDays() {
		return this.paidDays;
	}

	public void setPaidDays(String paidDays) {
		this.paidDays = paidDays;
	}

	@Column(name = "leave")
	public String getLeave() {
		return this.leave;
	}

	public void setLeave(String leave) {
		this.leave = leave;
	}

	@Column(name = "salary")
	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	@Column(name = "ded")
	public String getDed() {
		return this.ded;
	}

	public void setDed(String ded) {
		this.ded = ded;
	}

	@Column(name = "pf_amount")
	public String getPfAmount() {
		return this.pfAmount;
	}

	public void setPfAmount(String pfAmount) {
		this.pfAmount = pfAmount;
	}

	@Column(name = "other_allowance")
	public String getOtherAllowance() {
		return this.otherAllowance;
	}

	public void setOtherAllowance(String otherAllowance) {
		this.otherAllowance = otherAllowance;
	}

	@Column(name = "incentive", nullable = false)
	public String getIncentive() {
		return this.incentive;
	}

	public void setIncentive(String incentive) {
		this.incentive = incentive;
	}

	@Column(name = "allow_paid")
	public String getAllowPaid() {
		return this.allowPaid;
	}

	public void setAllowPaid(String allowPaid) {
		this.allowPaid = allowPaid;
	}

	@Column(name = "net_payable")
	public String getNetPayable() {
		return this.netPayable;
	}

	public void setNetPayable(String netPayable) {
		this.netPayable = netPayable;
	}

	@Column(name = "narration", length = 65535)
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	@Column(name = "pf_salary")
	public String getPfSalary() {
		return this.pfSalary;
	}

	public void setPfSalary(String pfSalary) {
		this.pfSalary = pfSalary;
	}

	@Column(name = "CL")
	public String getCl() {
		return this.cl;
	}

	public void setCl(String cl) {
		this.cl = cl;
	}

	@Column(name = "CCL")
	public String getCcl() {
		return this.ccl;
	}

	public void setCcl(String ccl) {
		this.ccl = ccl;
	}

	@Column(name = "LWP")
	public String getLwp() {
		return this.lwp;
	}

	public void setLwp(String lwp) {
		this.lwp = lwp;
	}

	@Column(name = "ABSENT")
	public String getAbsent() {
		return this.absent;
	}

	public void setAbsent(String absent) {
		this.absent = absent;
	}

	@Column(name = "monthly_off")
	public String getMonthlyOff() {
		return this.monthlyOff;
	}

	public void setMonthlyOff(String monthlyOff) {
		this.monthlyOff = monthlyOff;
	}

	@Column(name = "total_month_day")
	public String getTotalMonthDay() {
		return this.totalMonthDay;
	}

	public void setTotalMonthDay(String totalMonthDay) {
		this.totalMonthDay = totalMonthDay;
	}

}
