package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FilestoreImage generated by hbm2java
 */
@Entity
@Table(name = "filestore_image")
public class FilestoreImage implements java.io.Serializable {

	private Integer id;
	private String name;
	private int originalFileId;
	private int thumbFileId;

	public FilestoreImage() {
	}

	public FilestoreImage(int originalFileId, int thumbFileId) {
		this.originalFileId = originalFileId;
		this.thumbFileId = thumbFileId;
	}

	public FilestoreImage(String name, int originalFileId, int thumbFileId) {
		this.name = name;
		this.originalFileId = originalFileId;
		this.thumbFileId = thumbFileId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "original_file_id", nullable = false)
	public int getOriginalFileId() {
		return this.originalFileId;
	}

	public void setOriginalFileId(int originalFileId) {
		this.originalFileId = originalFileId;
	}

	@Column(name = "thumb_file_id", nullable = false)
	public int getThumbFileId() {
		return this.thumbFileId;
	}

	public void setThumbFileId(int thumbFileId) {
		this.thumbFileId = thumbFileId;
	}

}
