package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FilestoreFile generated by hbm2java
 */
@Entity
@Table(name = "filestore_file")
public class FilestoreFile implements java.io.Serializable {

	private Integer id;
	private int filestoreTypeId;
	private int filestoreVolumeId;
	private String filename;
	private String originalFilename;
	private int filesize;
	private int filenum;
	private String deleted;

	public FilestoreFile() {
	}

	public FilestoreFile(int filestoreTypeId, int filestoreVolumeId, String filename, int filesize, int filenum) {
		this.filestoreTypeId = filestoreTypeId;
		this.filestoreVolumeId = filestoreVolumeId;
		this.filename = filename;
		this.filesize = filesize;
		this.filenum = filenum;
	}

	public FilestoreFile(int filestoreTypeId, int filestoreVolumeId, String filename, String originalFilename,
			int filesize, int filenum, String deleted) {
		this.filestoreTypeId = filestoreTypeId;
		this.filestoreVolumeId = filestoreVolumeId;
		this.filename = filename;
		this.originalFilename = originalFilename;
		this.filesize = filesize;
		this.filenum = filenum;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "filestore_type_id", nullable = false)
	public int getFilestoreTypeId() {
		return this.filestoreTypeId;
	}

	public void setFilestoreTypeId(int filestoreTypeId) {
		this.filestoreTypeId = filestoreTypeId;
	}

	@Column(name = "filestore_volume_id", nullable = false)
	public int getFilestoreVolumeId() {
		return this.filestoreVolumeId;
	}

	public void setFilestoreVolumeId(int filestoreVolumeId) {
		this.filestoreVolumeId = filestoreVolumeId;
	}

	@Column(name = "filename", nullable = false)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "original_filename")
	public String getOriginalFilename() {
		return this.originalFilename;
	}

	public void setOriginalFilename(String originalFilename) {
		this.originalFilename = originalFilename;
	}

	@Column(name = "filesize", nullable = false)
	public int getFilesize() {
		return this.filesize;
	}

	public void setFilesize(int filesize) {
		this.filesize = filesize;
	}

	@Column(name = "filenum", nullable = false)
	public int getFilenum() {
		return this.filenum;
	}

	public void setFilenum(int filenum) {
		this.filenum = filenum;
	}

	@Column(name = "deleted", length = 2)
	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

}
