package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FilestoreType generated by hbm2java
 */
@Entity
@Table(name = "filestore_type")
public class FilestoreType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String mimeType;
	private String extension;

	public FilestoreType() {
	}

	public FilestoreType(String mimeType) {
		this.mimeType = mimeType;
	}

	public FilestoreType(String name, String mimeType, String extension) {
		this.name = name;
		this.mimeType = mimeType;
		this.extension = extension;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "mime_type", nullable = false, length = 64)
	public String getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	@Column(name = "extension", length = 5)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

}
