package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JosXatkAttendance generated by hbm2java
 */
@Entity
@Table(name = "jos_xatk_attendance")
public class JosXatkAttendance implements java.io.Serializable {

	private Integer id;
	private int empId;
	private Date createdAt;
	private int timeHour;
	private int timeMinute;
	private String mode;

	public JosXatkAttendance() {
	}

	public JosXatkAttendance(int empId, Date createdAt, int timeHour, int timeMinute, String mode) {
		this.empId = empId;
		this.createdAt = createdAt;
		this.timeHour = timeHour;
		this.timeMinute = timeMinute;
		this.mode = mode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "emp_id", nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "TimeHour", nullable = false)
	public int getTimeHour() {
		return this.timeHour;
	}

	public void setTimeHour(int timeHour) {
		this.timeHour = timeHour;
	}

	@Column(name = "TimeMinute", nullable = false)
	public int getTimeMinute() {
		return this.timeMinute;
	}

	public void setTimeMinute(int timeMinute) {
		this.timeMinute = timeMinute;
	}

	@Column(name = "Mode", nullable = false, length = 2)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

}
