package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JosXstockLog generated by hbm2java
 */
@Entity
@Table(name = "jos_xstock_log")
public class JosXstockLog implements java.io.Serializable {

	private Integer id;
	private Date stockAllotedDate;
	private Integer branchId;
	private Integer quantityAlloted;
	private Integer stockStatus;
	private int itemsId;

	public JosXstockLog() {
	}

	public JosXstockLog(int itemsId) {
		this.itemsId = itemsId;
	}

	public JosXstockLog(Date stockAllotedDate, Integer branchId, Integer quantityAlloted, Integer stockStatus,
			int itemsId) {
		this.stockAllotedDate = stockAllotedDate;
		this.branchId = branchId;
		this.quantityAlloted = quantityAlloted;
		this.stockStatus = stockStatus;
		this.itemsId = itemsId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StockAllotedDate", length = 19)
	public Date getStockAllotedDate() {
		return this.stockAllotedDate;
	}

	public void setStockAllotedDate(Date stockAllotedDate) {
		this.stockAllotedDate = stockAllotedDate;
	}

	@Column(name = "branch_id")
	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	@Column(name = "QuantityAlloted")
	public Integer getQuantityAlloted() {
		return this.quantityAlloted;
	}

	public void setQuantityAlloted(Integer quantityAlloted) {
		this.quantityAlloted = quantityAlloted;
	}

	@Column(name = "StockStatus")
	public Integer getStockStatus() {
		return this.stockStatus;
	}

	public void setStockStatus(Integer stockStatus) {
		this.stockStatus = stockStatus;
	}

	@Column(name = "items_id", nullable = false)
	public int getItemsId() {
		return this.itemsId;
	}

	public void setItemsId(int itemsId) {
		this.itemsId = itemsId;
	}

}
