package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JosXtemp generated by hbm2java
 */
@Entity
@Table(name = "jos_xtemp")
public class JosXtemp implements java.io.Serializable {

	private Integer id;
	private String accountNumber;
	private String loanFromAccountPrevious;
	private String loanFromAccountNew;
	private Boolean taskdone;

	public JosXtemp() {
	}

	public JosXtemp(String accountNumber, String loanFromAccountPrevious, String loanFromAccountNew, Boolean taskdone) {
		this.accountNumber = accountNumber;
		this.loanFromAccountPrevious = loanFromAccountPrevious;
		this.loanFromAccountNew = loanFromAccountNew;
		this.taskdone = taskdone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "AccountNumber", length = 100)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "LoanFromAccountPrevious", length = 100)
	public String getLoanFromAccountPrevious() {
		return this.loanFromAccountPrevious;
	}

	public void setLoanFromAccountPrevious(String loanFromAccountPrevious) {
		this.loanFromAccountPrevious = loanFromAccountPrevious;
	}

	@Column(name = "LoanFromAccountNew", length = 100)
	public String getLoanFromAccountNew() {
		return this.loanFromAccountNew;
	}

	public void setLoanFromAccountNew(String loanFromAccountNew) {
		this.loanFromAccountNew = loanFromAccountNew;
	}

	@Column(name = "taskdone")
	public Boolean getTaskdone() {
		return this.taskdone;
	}

	public void setTaskdone(Boolean taskdone) {
		this.taskdone = taskdone;
	}

}
