package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JosXagentcommissionreport generated by hbm2java
 */
@Entity
@Table(name = "jos_xagentcommissionreport")
public class JosXagentcommissionreport implements java.io.Serializable {

	private Integer id;
	private Integer agentsId;
	private Integer collectorId;
	private Integer accountsId;
	private String commission;
	private String collection;
	private Date commissionPayableDate;
	private Date commissionPaidDate;
	private String narration;

	public JosXagentcommissionreport() {
	}

	public JosXagentcommissionreport(Integer agentsId, Integer collectorId, Integer accountsId, String commission,
			String collection, Date commissionPayableDate, Date commissionPaidDate, String narration) {
		this.agentsId = agentsId;
		this.collectorId = collectorId;
		this.accountsId = accountsId;
		this.commission = commission;
		this.collection = collection;
		this.commissionPayableDate = commissionPayableDate;
		this.commissionPaidDate = commissionPaidDate;
		this.narration = narration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "agents_id")
	public Integer getAgentsId() {
		return this.agentsId;
	}

	public void setAgentsId(Integer agentsId) {
		this.agentsId = agentsId;
	}

	@Column(name = "collector_id")
	public Integer getCollectorId() {
		return this.collectorId;
	}

	public void setCollectorId(Integer collectorId) {
		this.collectorId = collectorId;
	}

	@Column(name = "accounts_id")
	public Integer getAccountsId() {
		return this.accountsId;
	}

	public void setAccountsId(Integer accountsId) {
		this.accountsId = accountsId;
	}

	@Column(name = "Commission", length = 10)
	public String getCommission() {
		return this.commission;
	}

	public void setCommission(String commission) {
		this.commission = commission;
	}

	@Column(name = "Collection", length = 10)
	public String getCollection() {
		return this.collection;
	}

	public void setCollection(String collection) {
		this.collection = collection;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CommissionPayableDate", length = 19)
	public Date getCommissionPayableDate() {
		return this.commissionPayableDate;
	}

	public void setCommissionPayableDate(Date commissionPayableDate) {
		this.commissionPayableDate = commissionPayableDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CommissionPaidDate", length = 19)
	public Date getCommissionPaidDate() {
		return this.commissionPaidDate;
	}

	public void setCommissionPaidDate(Date commissionPaidDate) {
		this.commissionPaidDate = commissionPaidDate;
	}

	@Column(name = "Narration", length = 200)
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

}
