package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JosXjointmembers generated by hbm2java
 */
@Entity
@Table(name = "jos_xjointmembers")
public class JosXjointmembers implements java.io.Serializable {

	private Integer id;
	private int accountsId;
	private int memberId;

	public JosXjointmembers() {
	}

	public JosXjointmembers(int accountsId, int memberId) {
		this.accountsId = accountsId;
		this.memberId = memberId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "accounts_id", nullable = false)
	public int getAccountsId() {
		return this.accountsId;
	}

	public void setAccountsId(int accountsId) {
		this.accountsId = accountsId;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

}
