package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JosXcommissionslab generated by hbm2java
 */
@Entity
@Table(name = "jos_xcommissionslab")
public class JosXcommissionslab implements java.io.Serializable {

	private Integer id;
	private Integer rank;
	private String advisorLevel;
	private Long totalCreditBusinessForPromotion;
	private String totalAdvisors;
	private Integer level1;
	private Integer level2;
	private Integer level3;
	private Integer level4;
	private Integer level5;
	private Integer level6;
	private Integer level7;
	private Integer level8;
	private Integer level9;
	private Integer level10;
	private Integer level11;
	private Integer level12;
	private Integer level13;
	private Integer level14;
	private Integer level15;
	private Integer level16;

	public JosXcommissionslab() {
	}

	public JosXcommissionslab(Integer rank, String advisorLevel, Long totalCreditBusinessForPromotion,
			String totalAdvisors, Integer level1, Integer level2, Integer level3, Integer level4, Integer level5,
			Integer level6, Integer level7, Integer level8, Integer level9, Integer level10, Integer level11,
			Integer level12, Integer level13, Integer level14, Integer level15, Integer level16) {
		this.rank = rank;
		this.advisorLevel = advisorLevel;
		this.totalCreditBusinessForPromotion = totalCreditBusinessForPromotion;
		this.totalAdvisors = totalAdvisors;
		this.level1 = level1;
		this.level2 = level2;
		this.level3 = level3;
		this.level4 = level4;
		this.level5 = level5;
		this.level6 = level6;
		this.level7 = level7;
		this.level8 = level8;
		this.level9 = level9;
		this.level10 = level10;
		this.level11 = level11;
		this.level12 = level12;
		this.level13 = level13;
		this.level14 = level14;
		this.level15 = level15;
		this.level16 = level16;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	@Column(name = "AdvisorLevel", length = 100)
	public String getAdvisorLevel() {
		return this.advisorLevel;
	}

	public void setAdvisorLevel(String advisorLevel) {
		this.advisorLevel = advisorLevel;
	}

	@Column(name = "TotalCreditBusinessForPromotion")
	public Long getTotalCreditBusinessForPromotion() {
		return this.totalCreditBusinessForPromotion;
	}

	public void setTotalCreditBusinessForPromotion(Long totalCreditBusinessForPromotion) {
		this.totalCreditBusinessForPromotion = totalCreditBusinessForPromotion;
	}

	@Column(name = "TotalAdvisors", length = 100)
	public String getTotalAdvisors() {
		return this.totalAdvisors;
	}

	public void setTotalAdvisors(String totalAdvisors) {
		this.totalAdvisors = totalAdvisors;
	}

	@Column(name = "Level1")
	public Integer getLevel1() {
		return this.level1;
	}

	public void setLevel1(Integer level1) {
		this.level1 = level1;
	}

	@Column(name = "Level2")
	public Integer getLevel2() {
		return this.level2;
	}

	public void setLevel2(Integer level2) {
		this.level2 = level2;
	}

	@Column(name = "Level3")
	public Integer getLevel3() {
		return this.level3;
	}

	public void setLevel3(Integer level3) {
		this.level3 = level3;
	}

	@Column(name = "Level4")
	public Integer getLevel4() {
		return this.level4;
	}

	public void setLevel4(Integer level4) {
		this.level4 = level4;
	}

	@Column(name = "Level5")
	public Integer getLevel5() {
		return this.level5;
	}

	public void setLevel5(Integer level5) {
		this.level5 = level5;
	}

	@Column(name = "Level6")
	public Integer getLevel6() {
		return this.level6;
	}

	public void setLevel6(Integer level6) {
		this.level6 = level6;
	}

	@Column(name = "Level7")
	public Integer getLevel7() {
		return this.level7;
	}

	public void setLevel7(Integer level7) {
		this.level7 = level7;
	}

	@Column(name = "Level8")
	public Integer getLevel8() {
		return this.level8;
	}

	public void setLevel8(Integer level8) {
		this.level8 = level8;
	}

	@Column(name = "Level9")
	public Integer getLevel9() {
		return this.level9;
	}

	public void setLevel9(Integer level9) {
		this.level9 = level9;
	}

	@Column(name = "Level10")
	public Integer getLevel10() {
		return this.level10;
	}

	public void setLevel10(Integer level10) {
		this.level10 = level10;
	}

	@Column(name = "Level11")
	public Integer getLevel11() {
		return this.level11;
	}

	public void setLevel11(Integer level11) {
		this.level11 = level11;
	}

	@Column(name = "Level12")
	public Integer getLevel12() {
		return this.level12;
	}

	public void setLevel12(Integer level12) {
		this.level12 = level12;
	}

	@Column(name = "Level13")
	public Integer getLevel13() {
		return this.level13;
	}

	public void setLevel13(Integer level13) {
		this.level13 = level13;
	}

	@Column(name = "Level14")
	public Integer getLevel14() {
		return this.level14;
	}

	public void setLevel14(Integer level14) {
		this.level14 = level14;
	}

	@Column(name = "Level15")
	public Integer getLevel15() {
		return this.level15;
	}

	public void setLevel15(Integer level15) {
		this.level15 = level15;
	}

	@Column(name = "Level16")
	public Integer getLevel16() {
		return this.level16;
	}

	public void setLevel16(Integer level16) {
		this.level16 = level16;
	}

}
