package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JosXstaffDetails generated by hbm2java
 */
@Entity
@Table(name = "jos_xstaff_details")
public class JosXstaffDetails implements java.io.Serializable {

	private Integer id;
	private Date joiningDate;
	private String basicPay;
	private String pf;
	private String variablePay;
	private String savingAccount;
	private int staffId;
	private String name;
	private String fatherName;
	private String presentAddress;
	private String permanentAddress;
	private String mobileNo;
	private String landlineNo;
	private Date dob;
	private String otherDetails;

	public JosXstaffDetails() {
	}

	public JosXstaffDetails(int staffId) {
		this.staffId = staffId;
	}

	public JosXstaffDetails(Date joiningDate, String basicPay, String pf, String variablePay, String savingAccount,
			int staffId, String name, String fatherName, String presentAddress, String permanentAddress,
			String mobileNo, String landlineNo, Date dob, String otherDetails) {
		this.joiningDate = joiningDate;
		this.basicPay = basicPay;
		this.pf = pf;
		this.variablePay = variablePay;
		this.savingAccount = savingAccount;
		this.staffId = staffId;
		this.name = name;
		this.fatherName = fatherName;
		this.presentAddress = presentAddress;
		this.permanentAddress = permanentAddress;
		this.mobileNo = mobileNo;
		this.landlineNo = landlineNo;
		this.dob = dob;
		this.otherDetails = otherDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JoiningDate", length = 19)
	public Date getJoiningDate() {
		return this.joiningDate;
	}

	public void setJoiningDate(Date joiningDate) {
		this.joiningDate = joiningDate;
	}

	@Column(name = "BasicPay", length = 45)
	public String getBasicPay() {
		return this.basicPay;
	}

	public void setBasicPay(String basicPay) {
		this.basicPay = basicPay;
	}

	@Column(name = "PF", length = 45)
	public String getPf() {
		return this.pf;
	}

	public void setPf(String pf) {
		this.pf = pf;
	}

	@Column(name = "VariablePay", length = 45)
	public String getVariablePay() {
		return this.variablePay;
	}

	public void setVariablePay(String variablePay) {
		this.variablePay = variablePay;
	}

	@Column(name = "SavingAccount", length = 45)
	public String getSavingAccount() {
		return this.savingAccount;
	}

	public void setSavingAccount(String savingAccount) {
		this.savingAccount = savingAccount;
	}

	@Column(name = "staff_id", nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@Column(name = "Name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "FatherName", length = 45)
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "PresentAddress", length = 200)
	public String getPresentAddress() {
		return this.presentAddress;
	}

	public void setPresentAddress(String presentAddress) {
		this.presentAddress = presentAddress;
	}

	@Column(name = "PermanentAddress", length = 200)
	public String getPermanentAddress() {
		return this.permanentAddress;
	}

	public void setPermanentAddress(String permanentAddress) {
		this.permanentAddress = permanentAddress;
	}

	@Column(name = "MobileNo", length = 15)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "LandlineNo", length = 25)
	public String getLandlineNo() {
		return this.landlineNo;
	}

	public void setLandlineNo(String landlineNo) {
		this.landlineNo = landlineNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOB", length = 19)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "OtherDetails", length = 200)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

}
