package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JosXstaffAttendance generated by hbm2java
 */
@Entity
@Table(name = "jos_xstaff_attendance")
public class JosXstaffAttendance implements java.io.Serializable {

	private Integer id;
	private Date date;
	private String attendance;
	private String narration;
	private int staffId;

	public JosXstaffAttendance() {
	}

	public JosXstaffAttendance(int staffId) {
		this.staffId = staffId;
	}

	public JosXstaffAttendance(Date date, String attendance, String narration, int staffId) {
		this.date = date;
		this.attendance = attendance;
		this.narration = narration;
		this.staffId = staffId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Attendance", length = 45)
	public String getAttendance() {
		return this.attendance;
	}

	public void setAttendance(String attendance) {
		this.attendance = attendance;
	}

	@Column(name = "Narration", length = 200)
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	@Column(name = "staff_id", nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

}
