package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JosXstaffPayments generated by hbm2java
 */
@Entity
@Table(name = "jos_xstaff_payments")
public class JosXstaffPayments implements java.io.Serializable {

	private Integer id;
	private Date date;
	private String payment;
	private String paymentAgainst;
	private int staffId;

	public JosXstaffPayments() {
	}

	public JosXstaffPayments(int staffId) {
		this.staffId = staffId;
	}

	public JosXstaffPayments(Date date, String payment, String paymentAgainst, int staffId) {
		this.date = date;
		this.payment = payment;
		this.paymentAgainst = paymentAgainst;
		this.staffId = staffId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Payment", length = 45)
	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	@Column(name = "PaymentAgainst", length = 45)
	public String getPaymentAgainst() {
		return this.paymentAgainst;
	}

	public void setPaymentAgainst(String paymentAgainst) {
		this.paymentAgainst = paymentAgainst;
	}

	@Column(name = "staff_id", nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

}
