package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JosXatkLeavesAlloted generated by hbm2java
 */
@Entity
@Table(name = "jos_xatk_leaves_alloted")
public class JosXatkLeavesAlloted implements java.io.Serializable {

	private Integer id;
	private int empId;
	private Date createdAt;
	private int leaves;
	private String narretion;

	public JosXatkLeavesAlloted() {
	}

	public JosXatkLeavesAlloted(int empId, Date createdAt, int leaves, String narretion) {
		this.empId = empId;
		this.createdAt = createdAt;
		this.leaves = leaves;
		this.narretion = narretion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "emp_id", nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created_At", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "Leaves", nullable = false)
	public int getLeaves() {
		return this.leaves;
	}

	public void setLeaves(int leaves) {
		this.leaves = leaves;
	}

	@Column(name = "Narretion", nullable = false, length = 65535)
	public String getNarretion() {
		return this.narretion;
	}

	public void setNarretion(String narretion) {
		this.narretion = narretion;
	}

}
