package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JosXatkEmployee generated by hbm2java
 */
@Entity
@Table(name = "jos_xatk_employee")
public class JosXatkEmployee implements java.io.Serializable {

	private Integer id;
	private int branchId;
	private String name;
	private String fatherName;
	private String presentAddress;
	private String permanentAddress;
	private int mobileNo;
	private int landlineNo;
	private Date dob;
	private String otherDetails;
	private int salary;
	private int allownces;
	private int pfsalary;
	private byte isPfapplicable;
	private int pfamount;
	private int tdsamount;
	private int accountNumber;
	private String bankName;
	private int salaryMode;
	private byte isActive;

	public JosXatkEmployee() {
	}

	public JosXatkEmployee(int branchId, String name, String fatherName, String presentAddress, String permanentAddress,
			int mobileNo, int landlineNo, Date dob, String otherDetails, int salary, int allownces, int pfsalary,
			byte isPfapplicable, int pfamount, int tdsamount, int accountNumber, String bankName, int salaryMode,
			byte isActive) {
		this.branchId = branchId;
		this.name = name;
		this.fatherName = fatherName;
		this.presentAddress = presentAddress;
		this.permanentAddress = permanentAddress;
		this.mobileNo = mobileNo;
		this.landlineNo = landlineNo;
		this.dob = dob;
		this.otherDetails = otherDetails;
		this.salary = salary;
		this.allownces = allownces;
		this.pfsalary = pfsalary;
		this.isPfapplicable = isPfapplicable;
		this.pfamount = pfamount;
		this.tdsamount = tdsamount;
		this.accountNumber = accountNumber;
		this.bankName = bankName;
		this.salaryMode = salaryMode;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "branch_id", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "FatherName", nullable = false)
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "PresentAddress", nullable = false, length = 65535)
	public String getPresentAddress() {
		return this.presentAddress;
	}

	public void setPresentAddress(String presentAddress) {
		this.presentAddress = presentAddress;
	}

	@Column(name = "PermanentAddress", nullable = false, length = 65535)
	public String getPermanentAddress() {
		return this.permanentAddress;
	}

	public void setPermanentAddress(String permanentAddress) {
		this.permanentAddress = permanentAddress;
	}

	@Column(name = "MobileNo", nullable = false)
	public int getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(int mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "LandlineNo", nullable = false)
	public int getLandlineNo() {
		return this.landlineNo;
	}

	public void setLandlineNo(int landlineNo) {
		this.landlineNo = landlineNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "OtherDetails", nullable = false, length = 65535)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	@Column(name = "Salary", nullable = false)
	public int getSalary() {
		return this.salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

	@Column(name = "Allownces", nullable = false)
	public int getAllownces() {
		return this.allownces;
	}

	public void setAllownces(int allownces) {
		this.allownces = allownces;
	}

	@Column(name = "PFSalary", nullable = false)
	public int getPfsalary() {
		return this.pfsalary;
	}

	public void setPfsalary(int pfsalary) {
		this.pfsalary = pfsalary;
	}

	@Column(name = "isPFApplicable", nullable = false)
	public byte getIsPfapplicable() {
		return this.isPfapplicable;
	}

	public void setIsPfapplicable(byte isPfapplicable) {
		this.isPfapplicable = isPfapplicable;
	}

	@Column(name = "PFAmount", nullable = false)
	public int getPfamount() {
		return this.pfamount;
	}

	public void setPfamount(int pfamount) {
		this.pfamount = pfamount;
	}

	@Column(name = "TDSAmount", nullable = false)
	public int getTdsamount() {
		return this.tdsamount;
	}

	public void setTdsamount(int tdsamount) {
		this.tdsamount = tdsamount;
	}

	@Column(name = "Account_Number", nullable = false)
	public int getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(int accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "Bank_Name", nullable = false)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "SalaryMode", nullable = false)
	public int getSalaryMode() {
		return this.salaryMode;
	}

	public void setSalaryMode(int salaryMode) {
		this.salaryMode = salaryMode;
	}

	@Column(name = "is_Active", nullable = false)
	public byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(byte isActive) {
		this.isActive = isActive;
	}

}
