package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JosXreports generated by hbm2java
 */
@Entity
@Table(name = "jos_xreports")
public class JosXreports implements java.io.Serializable {

	private Integer id;
	private String name;
	private String formFields;
	private String codeToRun;
	private String results;
	private String codeBeforeForm;
	private Byte published;
	private String reportTitle;

	public JosXreports() {
	}

	public JosXreports(String name, String formFields, String codeToRun, String results, String codeBeforeForm,
			Byte published, String reportTitle) {
		this.name = name;
		this.formFields = formFields;
		this.codeToRun = codeToRun;
		this.results = results;
		this.codeBeforeForm = codeBeforeForm;
		this.published = published;
		this.reportTitle = reportTitle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "formFields", length = 65535)
	public String getFormFields() {
		return this.formFields;
	}

	public void setFormFields(String formFields) {
		this.formFields = formFields;
	}

	@Column(name = "CodeToRun", length = 65535)
	public String getCodeToRun() {
		return this.codeToRun;
	}

	public void setCodeToRun(String codeToRun) {
		this.codeToRun = codeToRun;
	}

	@Column(name = "Results", length = 65535)
	public String getResults() {
		return this.results;
	}

	public void setResults(String results) {
		this.results = results;
	}

	@Column(name = "CodeBeforeForm", length = 65535)
	public String getCodeBeforeForm() {
		return this.codeBeforeForm;
	}

	public void setCodeBeforeForm(String codeBeforeForm) {
		this.codeBeforeForm = codeBeforeForm;
	}

	@Column(name = "published")
	public Byte getPublished() {
		return this.published;
	}

	public void setPublished(Byte published) {
		this.published = published;
	}

	@Column(name = "ReportTitle", length = 65535)
	public String getReportTitle() {
		return this.reportTitle;
	}

	public void setReportTitle(String reportTitle) {
		this.reportTitle = reportTitle;
	}

}
