package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JosXatkPayment generated by hbm2java
 */
@Entity
@Table(name = "jos_xatk_payment")
public class JosXatkPayment implements java.io.Serializable {

	private Integer id;
	private int empId;
	private int totalWorkingDays;
	private int presentDays;
	private int holiDays;
	private int sundays;
	private int leaves;
	private int leavesPaid;
	private int absent;
	private float salary;
	private int pfamount;
	private int deduction;
	private String monthYear;
	private String narration;
	private Date createdAt;

	public JosXatkPayment() {
	}

	public JosXatkPayment(int empId, int totalWorkingDays, int presentDays, int holiDays, int sundays, int leaves,
			int leavesPaid, int absent, float salary, int pfamount, int deduction, String monthYear, String narration,
			Date createdAt) {
		this.empId = empId;
		this.totalWorkingDays = totalWorkingDays;
		this.presentDays = presentDays;
		this.holiDays = holiDays;
		this.sundays = sundays;
		this.leaves = leaves;
		this.leavesPaid = leavesPaid;
		this.absent = absent;
		this.salary = salary;
		this.pfamount = pfamount;
		this.deduction = deduction;
		this.monthYear = monthYear;
		this.narration = narration;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "emp_id", nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Column(name = "TotalWorkingDays", nullable = false)
	public int getTotalWorkingDays() {
		return this.totalWorkingDays;
	}

	public void setTotalWorkingDays(int totalWorkingDays) {
		this.totalWorkingDays = totalWorkingDays;
	}

	@Column(name = "PresentDays", nullable = false)
	public int getPresentDays() {
		return this.presentDays;
	}

	public void setPresentDays(int presentDays) {
		this.presentDays = presentDays;
	}

	@Column(name = "HoliDays", nullable = false)
	public int getHoliDays() {
		return this.holiDays;
	}

	public void setHoliDays(int holiDays) {
		this.holiDays = holiDays;
	}

	@Column(name = "Sundays", nullable = false)
	public int getSundays() {
		return this.sundays;
	}

	public void setSundays(int sundays) {
		this.sundays = sundays;
	}

	@Column(name = "Leaves", nullable = false)
	public int getLeaves() {
		return this.leaves;
	}

	public void setLeaves(int leaves) {
		this.leaves = leaves;
	}

	@Column(name = "LeavesPaid", nullable = false)
	public int getLeavesPaid() {
		return this.leavesPaid;
	}

	public void setLeavesPaid(int leavesPaid) {
		this.leavesPaid = leavesPaid;
	}

	@Column(name = "Absent", nullable = false)
	public int getAbsent() {
		return this.absent;
	}

	public void setAbsent(int absent) {
		this.absent = absent;
	}

	@Column(name = "Salary", nullable = false, precision = 11)
	public float getSalary() {
		return this.salary;
	}

	public void setSalary(float salary) {
		this.salary = salary;
	}

	@Column(name = "PFAmount", nullable = false)
	public int getPfamount() {
		return this.pfamount;
	}

	public void setPfamount(int pfamount) {
		this.pfamount = pfamount;
	}

	@Column(name = "Deduction", nullable = false)
	public int getDeduction() {
		return this.deduction;
	}

	public void setDeduction(int deduction) {
		this.deduction = deduction;
	}

	@Column(name = "MonthYear", nullable = false, length = 6)
	public String getMonthYear() {
		return this.monthYear;
	}

	public void setMonthYear(String monthYear) {
		this.monthYear = monthYear;
	}

	@Column(name = "Narration", nullable = false, length = 65535)
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Created_At", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
