package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JosXeventsId generated by hbm2java
 */
@Embeddable
public class JosXeventsId implements java.io.Serializable {

	private int id;
	private int schemesId;

	public JosXeventsId() {
	}

	public JosXeventsId(int id, int schemesId) {
		this.id = id;
		this.schemesId = schemesId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "schemes_id", nullable = false)
	public int getSchemesId() {
		return this.schemesId;
	}

	public void setSchemesId(int schemesId) {
		this.schemesId = schemesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JosXeventsId))
			return false;
		JosXeventsId castOther = (JosXeventsId) other;

		return (this.getId() == castOther.getId()) && (this.getSchemesId() == castOther.getSchemesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getSchemesId();
		return result;
	}

}
