package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JosXcideveloperProjects generated by hbm2java
 */
@Entity
@Table(name = "jos_xcideveloper_projects")
public class JosXcideveloperProjects implements java.io.Serializable {

	private Integer id;
	private String component;
	private String comName;
	private String extensionType;
	private String params;
	private Byte published;
	private String manifest;

	public JosXcideveloperProjects() {
	}

	public JosXcideveloperProjects(String component, String comName) {
		this.component = component;
		this.comName = comName;
	}

	public JosXcideveloperProjects(String component, String comName, String extensionType, String params,
			Byte published, String manifest) {
		this.component = component;
		this.comName = comName;
		this.extensionType = extensionType;
		this.params = params;
		this.published = published;
		this.manifest = manifest;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "component", nullable = false, length = 50)
	public String getComponent() {
		return this.component;
	}

	public void setComponent(String component) {
		this.component = component;
	}

	@Column(name = "com_name", nullable = false, length = 50)
	public String getComName() {
		return this.comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	@Column(name = "extension_type")
	public String getExtensionType() {
		return this.extensionType;
	}

	public void setExtensionType(String extensionType) {
		this.extensionType = extensionType;
	}

	@Column(name = "params", length = 65535)
	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	@Column(name = "published")
	public Byte getPublished() {
		return this.published;
	}

	public void setPublished(Byte published) {
		this.published = published;
	}

	@Column(name = "manifest", length = 65535)
	public String getManifest() {
		return this.manifest;
	}

	public void setManifest(String manifest) {
		this.manifest = manifest;
	}

}
