package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicUpdate;

/**
 * Members generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "members", uniqueConstraints = @UniqueConstraint(columnNames = "member_no"))
public class Members implements java.io.Serializable {

	private Integer id;
	private String name;
	private String currentAddress;
	private String fatherName;
	private String cast;
	private String permanentAddress;
	private String occupation;
	private String nominee;
	private String relationWithNominee;
	private Short nomineeAge;
	private String witness1name;
	private String witness1fatherName;
	private String witness1address;
	private String witness2name;
	private String witness2fatherName;
	private String witness2address;
	private Date createdAt;
	private Date updatedAt;
	private int branchId;
	private String phoneNos;
	private String panNo;
	private Boolean isMinor;
	private Date minorDob;
	private String parentName;
	private String relationWithParent;
	private Integer staffId;
	private Integer netmemberId;
	private String memberCode;
	private Date dob;
	private byte filledForm60;
	private String customerCode;
	private int parentMemberId;
	private Date customerCreatedAt;
	private String officeAddress;
	private String officePhoneNos;
	private String email;
	private String bloodGroup;
	private String maritalStatus;
	private Integer numberOfChildren;
	private Date marriageDate;
	private String highestQualification;
	private String occupationDetails;
	private String employerAddress;
	private String selfEmployeeDetails;
	private String familyMonthlyIncome;
	private String bank;
	private String branch;
	private String accountNumber;
	private String debitCreditCardNo;
	private String debitCreditCardIssuingBank;
	private String passportNo;
	private String passportIssuedAt;
	private Byte employerCard;
	private Byte passport;
	private Byte panCard;
	private Byte voterIdCard;
	private Byte drivingLicense;
	private Byte govtArmyIdCard;
	private Byte rationCard;
	private Byte otherDocument;
	private String documentDescription;
	private Byte cameToKnowByNewspaper;
	private Byte cameToKnowByTelevision;
	private Byte cameToKnowByAdvertisement;
	private Byte cameToKnowByFriends;
	private Byte cameToKnowByFieldworker;
	private String otherDetails;
	private String title;
	private Boolean isAgent;
	private String landmark;
	private String tehsil;
	private String district;
	private String city;
	private String pinCode;
	private Integer docImageId;
	private String state;
	private String parentAddress;
	private Boolean isActive;
	private Boolean isDefaulter;
	private String username;
	private String password;
	private Integer memberNo;
	private Integer bankbranchAId;
	private String bankAccountNumber1;
	private Integer bankbranchBId;
	private String bankAccountNumber2;
	private String memebrType;
	private Date defaulterOn;
	private String adharNumber;
	private String gstin;
	private String relationWithFatherField;
	private Set comments = new HashSet(0);
	private Set documentsSubmitteds = new HashSet(0);
	private Set accountGuarantorses = new HashSet(0);
	private Set dsas = new HashSet(0);
	private Set agentGuarantorses = new HashSet(0);
	private Set dsaGuarantorses = new HashSet(0);
	private Set jointmemberses = new HashSet(0);

	public Members() {
	}

	public Members(int branchId, byte filledForm60, int parentMemberId, String username, String password) {
		this.branchId = branchId;
		this.filledForm60 = filledForm60;
		this.parentMemberId = parentMemberId;
		this.username = username;
		this.password = password;
	}

	public Members(String name, String currentAddress, String fatherName, String cast, String permanentAddress,
			String occupation, String nominee, String relationWithNominee, Short nomineeAge, String witness1name,
			String witness1fatherName, String witness1address, String witness2name, String witness2fatherName,
			String witness2address, Date createdAt, Date updatedAt, int branchId, String phoneNos, String panNo,
			Boolean isMinor, Date minorDob, String parentName, String relationWithParent, Integer staffId,
			Integer netmemberId, String memberCode, Date dob, byte filledForm60, String customerCode,
			int parentMemberId, Date customerCreatedAt, String officeAddress, String officePhoneNos, String email,
			String bloodGroup, String maritalStatus, Integer numberOfChildren, Date marriageDate,
			String highestQualification, String occupationDetails, String employerAddress, String selfEmployeeDetails,
			String familyMonthlyIncome, String bank, String branch, String accountNumber, String debitCreditCardNo,
			String debitCreditCardIssuingBank, String passportNo, String passportIssuedAt, Byte employerCard,
			Byte passport, Byte panCard, Byte voterIdCard, Byte drivingLicense, Byte govtArmyIdCard, Byte rationCard,
			Byte otherDocument, String documentDescription, Byte cameToKnowByNewspaper, Byte cameToKnowByTelevision,
			Byte cameToKnowByAdvertisement, Byte cameToKnowByFriends, Byte cameToKnowByFieldworker, String otherDetails,
			String title, Boolean isAgent, String landmark, String tehsil, String district, String city, String pinCode,
			Integer docImageId, String state, String parentAddress, Boolean isActive, Boolean isDefaulter,
			String username, String password, Integer memberNo, Integer bankbranchAId, String bankAccountNumber1,
			Integer bankbranchBId, String bankAccountNumber2, String memebrType, Date defaulterOn, String adharNumber,
			String gstin, String relationWithFatherField, Set comments, Set documentsSubmitteds,
			Set accountGuarantorses, Set dsas, Set agentGuarantorses, Set dsaGuarantorses, Set jointmemberses) {
		this.name = name;
		this.currentAddress = currentAddress;
		this.fatherName = fatherName;
		this.cast = cast;
		this.permanentAddress = permanentAddress;
		this.occupation = occupation;
		this.nominee = nominee;
		this.relationWithNominee = relationWithNominee;
		this.nomineeAge = nomineeAge;
		this.witness1name = witness1name;
		this.witness1fatherName = witness1fatherName;
		this.witness1address = witness1address;
		this.witness2name = witness2name;
		this.witness2fatherName = witness2fatherName;
		this.witness2address = witness2address;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.branchId = branchId;
		this.phoneNos = phoneNos;
		this.panNo = panNo;
		this.isMinor = isMinor;
		this.minorDob = minorDob;
		this.parentName = parentName;
		this.relationWithParent = relationWithParent;
		this.staffId = staffId;
		this.netmemberId = netmemberId;
		this.memberCode = memberCode;
		this.dob = dob;
		this.filledForm60 = filledForm60;
		this.customerCode = customerCode;
		this.parentMemberId = parentMemberId;
		this.customerCreatedAt = customerCreatedAt;
		this.officeAddress = officeAddress;
		this.officePhoneNos = officePhoneNos;
		this.email = email;
		this.bloodGroup = bloodGroup;
		this.maritalStatus = maritalStatus;
		this.numberOfChildren = numberOfChildren;
		this.marriageDate = marriageDate;
		this.highestQualification = highestQualification;
		this.occupationDetails = occupationDetails;
		this.employerAddress = employerAddress;
		this.selfEmployeeDetails = selfEmployeeDetails;
		this.familyMonthlyIncome = familyMonthlyIncome;
		this.bank = bank;
		this.branch = branch;
		this.accountNumber = accountNumber;
		this.debitCreditCardNo = debitCreditCardNo;
		this.debitCreditCardIssuingBank = debitCreditCardIssuingBank;
		this.passportNo = passportNo;
		this.passportIssuedAt = passportIssuedAt;
		this.employerCard = employerCard;
		this.passport = passport;
		this.panCard = panCard;
		this.voterIdCard = voterIdCard;
		this.drivingLicense = drivingLicense;
		this.govtArmyIdCard = govtArmyIdCard;
		this.rationCard = rationCard;
		this.otherDocument = otherDocument;
		this.documentDescription = documentDescription;
		this.cameToKnowByNewspaper = cameToKnowByNewspaper;
		this.cameToKnowByTelevision = cameToKnowByTelevision;
		this.cameToKnowByAdvertisement = cameToKnowByAdvertisement;
		this.cameToKnowByFriends = cameToKnowByFriends;
		this.cameToKnowByFieldworker = cameToKnowByFieldworker;
		this.otherDetails = otherDetails;
		this.title = title;
		this.isAgent = isAgent;
		this.landmark = landmark;
		this.tehsil = tehsil;
		this.district = district;
		this.city = city;
		this.pinCode = pinCode;
		this.docImageId = docImageId;
		this.state = state;
		this.parentAddress = parentAddress;
		this.isActive = isActive;
		this.isDefaulter = isDefaulter;
		this.username = username;
		this.password = password;
		this.memberNo = memberNo;
		this.bankbranchAId = bankbranchAId;
		this.bankAccountNumber1 = bankAccountNumber1;
		this.bankbranchBId = bankbranchBId;
		this.bankAccountNumber2 = bankAccountNumber2;
		this.memebrType = memebrType;
		this.defaulterOn = defaulterOn;
		this.adharNumber = adharNumber;
		this.gstin = gstin;
		this.relationWithFatherField = relationWithFatherField;
		this.comments = comments;
		this.documentsSubmitteds = documentsSubmitteds;
		this.accountGuarantorses = accountGuarantorses;
		this.dsas = dsas;
		this.agentGuarantorses = agentGuarantorses;
		this.dsaGuarantorses = dsaGuarantorses;
		this.jointmemberses = jointmemberses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CurrentAddress", length = 65535)
	public String getCurrentAddress() {
		return this.currentAddress;
	}

	public void setCurrentAddress(String currentAddress) {
		this.currentAddress = currentAddress;
	}

	@Column(name = "FatherName", length = 45)
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "Cast", length = 45)
	public String getCast() {
		return this.cast;
	}

	public void setCast(String cast) {
		this.cast = cast;
	}

	@Column(name = "PermanentAddress", length = 65535)
	public String getPermanentAddress() {
		return this.permanentAddress;
	}

	public void setPermanentAddress(String permanentAddress) {
		this.permanentAddress = permanentAddress;
	}

	@Column(name = "Occupation", length = 45)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "Nominee", length = 45)
	public String getNominee() {
		return this.nominee;
	}

	public void setNominee(String nominee) {
		this.nominee = nominee;
	}

	@Column(name = "RelationWithNominee", length = 45)
	public String getRelationWithNominee() {
		return this.relationWithNominee;
	}

	public void setRelationWithNominee(String relationWithNominee) {
		this.relationWithNominee = relationWithNominee;
	}

	@Column(name = "NomineeAge")
	public Short getNomineeAge() {
		return this.nomineeAge;
	}

	public void setNomineeAge(Short nomineeAge) {
		this.nomineeAge = nomineeAge;
	}

	@Column(name = "Witness1Name", length = 45)
	public String getWitness1name() {
		return this.witness1name;
	}

	public void setWitness1name(String witness1name) {
		this.witness1name = witness1name;
	}

	@Column(name = "Witness1FatherName", length = 45)
	public String getWitness1fatherName() {
		return this.witness1fatherName;
	}

	public void setWitness1fatherName(String witness1fatherName) {
		this.witness1fatherName = witness1fatherName;
	}

	@Column(name = "Witness1Address", length = 65535)
	public String getWitness1address() {
		return this.witness1address;
	}

	public void setWitness1address(String witness1address) {
		this.witness1address = witness1address;
	}

	@Column(name = "Witness2Name", length = 45)
	public String getWitness2name() {
		return this.witness2name;
	}

	public void setWitness2name(String witness2name) {
		this.witness2name = witness2name;
	}

	@Column(name = "Witness2FatherName", length = 45)
	public String getWitness2fatherName() {
		return this.witness2fatherName;
	}

	public void setWitness2fatherName(String witness2fatherName) {
		this.witness2fatherName = witness2fatherName;
	}

	@Column(name = "Witness2Address", length = 65535)
	public String getWitness2address() {
		return this.witness2address;
	}

	public void setWitness2address(String witness2address) {
		this.witness2address = witness2address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "branch_id", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	@Column(name = "PhoneNos", length = 65535)
	public String getPhoneNos() {
		return this.phoneNos;
	}

	public void setPhoneNos(String phoneNos) {
		this.phoneNos = phoneNos;
	}

	@Column(name = "PanNo", length = 10)
	public String getPanNo() {
		return this.panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	@Column(name = "IsMinor")
	public Boolean getIsMinor() {
		return this.isMinor;
	}

	public void setIsMinor(Boolean isMinor) {
		this.isMinor = isMinor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MinorDOB", length = 10)
	public Date getMinorDob() {
		return this.minorDob;
	}

	public void setMinorDob(Date minorDob) {
		this.minorDob = minorDob;
	}

	@Column(name = "ParentName", length = 45)
	public String getParentName() {
		return this.parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	@Column(name = "RelationWithParent", length = 45)
	public String getRelationWithParent() {
		return this.relationWithParent;
	}

	public void setRelationWithParent(String relationWithParent) {
		this.relationWithParent = relationWithParent;
	}

	@Column(name = "staff_id")
	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	@Column(name = "netmember_id")
	public Integer getNetmemberId() {
		return this.netmemberId;
	}

	public void setNetmemberId(Integer netmemberId) {
		this.netmemberId = netmemberId;
	}

	@Column(name = "MemberCode", length = 45)
	public String getMemberCode() {
		return this.memberCode;
	}

	public void setMemberCode(String memberCode) {
		this.memberCode = memberCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOB", length = 19)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "FilledForm60", nullable = false)
	public byte getFilledForm60() {
		return this.filledForm60;
	}

	public void setFilledForm60(byte filledForm60) {
		this.filledForm60 = filledForm60;
	}

	@Column(name = "CustomerCode", length = 45)
	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	@Column(name = "parent_member_id", nullable = false)
	public int getParentMemberId() {
		return this.parentMemberId;
	}

	public void setParentMemberId(int parentMemberId) {
		this.parentMemberId = parentMemberId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "customer_created_at", length = 19)
	public Date getCustomerCreatedAt() {
		return this.customerCreatedAt;
	}

	public void setCustomerCreatedAt(Date customerCreatedAt) {
		this.customerCreatedAt = customerCreatedAt;
	}

	@Column(name = "OfficeAddress", length = 200)
	public String getOfficeAddress() {
		return this.officeAddress;
	}

	public void setOfficeAddress(String officeAddress) {
		this.officeAddress = officeAddress;
	}

	@Column(name = "OfficePhoneNos", length = 100)
	public String getOfficePhoneNos() {
		return this.officePhoneNos;
	}

	public void setOfficePhoneNos(String officePhoneNos) {
		this.officePhoneNos = officePhoneNos;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "BloodGroup", length = 10)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name = "MaritalStatus", length = 20)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "NumberOfChildren")
	public Integer getNumberOfChildren() {
		return this.numberOfChildren;
	}

	public void setNumberOfChildren(Integer numberOfChildren) {
		this.numberOfChildren = numberOfChildren;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MarriageDate", length = 10)
	public Date getMarriageDate() {
		return this.marriageDate;
	}

	public void setMarriageDate(Date marriageDate) {
		this.marriageDate = marriageDate;
	}

	@Column(name = "HighestQualification", length = 50)
	public String getHighestQualification() {
		return this.highestQualification;
	}

	public void setHighestQualification(String highestQualification) {
		this.highestQualification = highestQualification;
	}

	@Column(name = "OccupationDetails", length = 50)
	public String getOccupationDetails() {
		return this.occupationDetails;
	}

	public void setOccupationDetails(String occupationDetails) {
		this.occupationDetails = occupationDetails;
	}

	@Column(name = "EmployerAddress", length = 200)
	public String getEmployerAddress() {
		return this.employerAddress;
	}

	public void setEmployerAddress(String employerAddress) {
		this.employerAddress = employerAddress;
	}

	@Column(name = "SelfEmployeeDetails", length = 100)
	public String getSelfEmployeeDetails() {
		return this.selfEmployeeDetails;
	}

	public void setSelfEmployeeDetails(String selfEmployeeDetails) {
		this.selfEmployeeDetails = selfEmployeeDetails;
	}

	@Column(name = "FamilyMonthlyIncome", length = 10)
	public String getFamilyMonthlyIncome() {
		return this.familyMonthlyIncome;
	}

	public void setFamilyMonthlyIncome(String familyMonthlyIncome) {
		this.familyMonthlyIncome = familyMonthlyIncome;
	}

	@Column(name = "Bank", length = 50)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	@Column(name = "Branch", length = 50)
	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	@Column(name = "AccountNumber", length = 30)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "DebitCreditCardNo", length = 45)
	public String getDebitCreditCardNo() {
		return this.debitCreditCardNo;
	}

	public void setDebitCreditCardNo(String debitCreditCardNo) {
		this.debitCreditCardNo = debitCreditCardNo;
	}

	@Column(name = "DebitCreditCardIssuingBank", length = 50)
	public String getDebitCreditCardIssuingBank() {
		return this.debitCreditCardIssuingBank;
	}

	public void setDebitCreditCardIssuingBank(String debitCreditCardIssuingBank) {
		this.debitCreditCardIssuingBank = debitCreditCardIssuingBank;
	}

	@Column(name = "PassportNo", length = 20)
	public String getPassportNo() {
		return this.passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	@Column(name = "PassportIssuedAt", length = 50)
	public String getPassportIssuedAt() {
		return this.passportIssuedAt;
	}

	public void setPassportIssuedAt(String passportIssuedAt) {
		this.passportIssuedAt = passportIssuedAt;
	}

	@Column(name = "EmployerCard")
	public Byte getEmployerCard() {
		return this.employerCard;
	}

	public void setEmployerCard(Byte employerCard) {
		this.employerCard = employerCard;
	}

	@Column(name = "Passport")
	public Byte getPassport() {
		return this.passport;
	}

	public void setPassport(Byte passport) {
		this.passport = passport;
	}

	@Column(name = "PanCard")
	public Byte getPanCard() {
		return this.panCard;
	}

	public void setPanCard(Byte panCard) {
		this.panCard = panCard;
	}

	@Column(name = "VoterIdCard")
	public Byte getVoterIdCard() {
		return this.voterIdCard;
	}

	public void setVoterIdCard(Byte voterIdCard) {
		this.voterIdCard = voterIdCard;
	}

	@Column(name = "DrivingLicense")
	public Byte getDrivingLicense() {
		return this.drivingLicense;
	}

	public void setDrivingLicense(Byte drivingLicense) {
		this.drivingLicense = drivingLicense;
	}

	@Column(name = "GovtArmyIdCard")
	public Byte getGovtArmyIdCard() {
		return this.govtArmyIdCard;
	}

	public void setGovtArmyIdCard(Byte govtArmyIdCard) {
		this.govtArmyIdCard = govtArmyIdCard;
	}

	@Column(name = "RationCard")
	public Byte getRationCard() {
		return this.rationCard;
	}

	public void setRationCard(Byte rationCard) {
		this.rationCard = rationCard;
	}

	@Column(name = "OtherDocument")
	public Byte getOtherDocument() {
		return this.otherDocument;
	}

	public void setOtherDocument(Byte otherDocument) {
		this.otherDocument = otherDocument;
	}

	@Column(name = "DocumentDescription", length = 100)
	public String getDocumentDescription() {
		return this.documentDescription;
	}

	public void setDocumentDescription(String documentDescription) {
		this.documentDescription = documentDescription;
	}

	@Column(name = "CameToKnowByNewspaper")
	public Byte getCameToKnowByNewspaper() {
		return this.cameToKnowByNewspaper;
	}

	public void setCameToKnowByNewspaper(Byte cameToKnowByNewspaper) {
		this.cameToKnowByNewspaper = cameToKnowByNewspaper;
	}

	@Column(name = "CameToKnowByTelevision")
	public Byte getCameToKnowByTelevision() {
		return this.cameToKnowByTelevision;
	}

	public void setCameToKnowByTelevision(Byte cameToKnowByTelevision) {
		this.cameToKnowByTelevision = cameToKnowByTelevision;
	}

	@Column(name = "CameToKnowByAdvertisement")
	public Byte getCameToKnowByAdvertisement() {
		return this.cameToKnowByAdvertisement;
	}

	public void setCameToKnowByAdvertisement(Byte cameToKnowByAdvertisement) {
		this.cameToKnowByAdvertisement = cameToKnowByAdvertisement;
	}

	@Column(name = "CameToKnowByFriends")
	public Byte getCameToKnowByFriends() {
		return this.cameToKnowByFriends;
	}

	public void setCameToKnowByFriends(Byte cameToKnowByFriends) {
		this.cameToKnowByFriends = cameToKnowByFriends;
	}

	@Column(name = "CameToKnowByFieldworker")
	public Byte getCameToKnowByFieldworker() {
		return this.cameToKnowByFieldworker;
	}

	public void setCameToKnowByFieldworker(Byte cameToKnowByFieldworker) {
		this.cameToKnowByFieldworker = cameToKnowByFieldworker;
	}

	@Column(name = "OtherDetails", length = 200)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "is_agent")
	public Boolean getIsAgent() {
		return this.isAgent;
	}

	public void setIsAgent(Boolean isAgent) {
		this.isAgent = isAgent;
	}

	@Column(name = "landmark")
	public String getLandmark() {
		return this.landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	@Column(name = "tehsil")
	public String getTehsil() {
		return this.tehsil;
	}

	public void setTehsil(String tehsil) {
		this.tehsil = tehsil;
	}

	@Column(name = "district")
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "pin_code")
	public String getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "doc_image_id")
	public Integer getDocImageId() {
		return this.docImageId;
	}

	public void setDocImageId(Integer docImageId) {
		this.docImageId = docImageId;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ParentAddress", length = 65535)
	public String getParentAddress() {
		return this.parentAddress;
	}

	public void setParentAddress(String parentAddress) {
		this.parentAddress = parentAddress;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "is_defaulter")
	public Boolean getIsDefaulter() {
		return this.isDefaulter;
	}

	public void setIsDefaulter(Boolean isDefaulter) {
		this.isDefaulter = isDefaulter;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "member_no", unique = true)
	public Integer getMemberNo() {
		return this.memberNo;
	}

	public void setMemberNo(Integer memberNo) {
		this.memberNo = memberNo;
	}

	@Column(name = "bankbranch_a_id")
	public Integer getBankbranchAId() {
		return this.bankbranchAId;
	}

	public void setBankbranchAId(Integer bankbranchAId) {
		this.bankbranchAId = bankbranchAId;
	}

	@Column(name = "bank_account_number_1")
	public String getBankAccountNumber1() {
		return this.bankAccountNumber1;
	}

	public void setBankAccountNumber1(String bankAccountNumber1) {
		this.bankAccountNumber1 = bankAccountNumber1;
	}

	@Column(name = "bankbranch_b_id")
	public Integer getBankbranchBId() {
		return this.bankbranchBId;
	}

	public void setBankbranchBId(Integer bankbranchBId) {
		this.bankbranchBId = bankbranchBId;
	}

	@Column(name = "bank_account_number_2")
	public String getBankAccountNumber2() {
		return this.bankAccountNumber2;
	}

	public void setBankAccountNumber2(String bankAccountNumber2) {
		this.bankAccountNumber2 = bankAccountNumber2;
	}

	@Column(name = "memebr_type")
	public String getMemebrType() {
		return this.memebrType;
	}

	public void setMemebrType(String memebrType) {
		this.memebrType = memebrType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "defaulter_on", length = 19)
	public Date getDefaulterOn() {
		return this.defaulterOn;
	}

	public void setDefaulterOn(Date defaulterOn) {
		this.defaulterOn = defaulterOn;
	}

	@Column(name = "AdharNumber")
	public String getAdharNumber() {
		return this.adharNumber;
	}

	public void setAdharNumber(String adharNumber) {
		this.adharNumber = adharNumber;
	}

	@Column(name = "gstin")
	public String getGstin() {
		return this.gstin;
	}

	public void setGstin(String gstin) {
		this.gstin = gstin;
	}

	@Column(name = "RelationWithFatherField")
	public String getRelationWithFatherField() {
		return this.relationWithFatherField;
	}

	public void setRelationWithFatherField(String relationWithFatherField) {
		this.relationWithFatherField = relationWithFatherField;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<DocumentsSubmitted> getDocumentsSubmitteds() {
		return this.documentsSubmitteds;
	}

	public void setDocumentsSubmitteds(Set documentsSubmitteds) {
		this.documentsSubmitteds = documentsSubmitteds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<AccountGuarantors> getAccountGuarantorses() {
		return this.accountGuarantorses;
	}

	public void setAccountGuarantorses(Set accountGuarantorses) {
		this.accountGuarantorses = accountGuarantorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<Dsa> getDsas() {
		return this.dsas;
	}

	public void setDsas(Set dsas) {
		this.dsas = dsas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<AgentGuarantors> getAgentGuarantorses() {
		return this.agentGuarantorses;
	}

	public void setAgentGuarantorses(Set agentGuarantorses) {
		this.agentGuarantorses = agentGuarantorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<DsaGuarantors> getDsaGuarantorses() {
		return this.dsaGuarantorses;
	}

	public void setDsaGuarantorses(Set dsaGuarantorses) {
		this.dsaGuarantorses = dsaGuarantorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<Jointmembers> getJointmemberses() {
		return this.jointmemberses;
	}

	public void setJointmemberses(Set jointmemberses) {
		this.jointmemberses = jointmemberses;
	}

}
