package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberDocumnets generated by hbm2java
 */
@Entity
@Table(name = "member_documnets")
public class MemberDocumnets implements java.io.Serializable {

	private Integer id;
	private int accountsId;
	private int memberId;
	private String name;
	private int docImageId;
	private String description;
	private Date submittedOn;

	public MemberDocumnets() {
	}

	public MemberDocumnets(int accountsId, int memberId, String name, int docImageId, String description,
			Date submittedOn) {
		this.accountsId = accountsId;
		this.memberId = memberId;
		this.name = name;
		this.docImageId = docImageId;
		this.description = description;
		this.submittedOn = submittedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "accounts_id", nullable = false)
	public int getAccountsId() {
		return this.accountsId;
	}

	public void setAccountsId(int accountsId) {
		this.accountsId = accountsId;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "doc_image_id", nullable = false)
	public int getDocImageId() {
		return this.docImageId;
	}

	public void setDocImageId(int docImageId) {
		this.docImageId = docImageId;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "submitted_on", nullable = false, length = 19)
	public Date getSubmittedOn() {
		return this.submittedOn;
	}

	public void setSubmittedOn(Date submittedOn) {
		this.submittedOn = submittedOn;
	}

}
