package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemorandumTransactions generated by hbm2java
 */
@Entity
@Table(name = "memorandum_transactions")
public class MemorandumTransactions implements java.io.Serializable {

	private Integer id;
	private int staffId;
	private int branchId;
	private int name;
	private String memorandumType;
	private String narration;
	private Date createdAt;

	public MemorandumTransactions() {
	}

	public MemorandumTransactions(int staffId, int branchId, int name, String memorandumType, String narration,
			Date createdAt) {
		this.staffId = staffId;
		this.branchId = branchId;
		this.name = name;
		this.memorandumType = memorandumType;
		this.narration = narration;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "staff_id", nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@Column(name = "branch_id", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	@Column(name = "name", nullable = false)
	public int getName() {
		return this.name;
	}

	public void setName(int name) {
		this.name = name;
	}

	@Column(name = "memorandum_type", nullable = false)
	public String getMemorandumType() {
		return this.memorandumType;
	}

	public void setMemorandumType(String memorandumType) {
		this.memorandumType = memorandumType;
	}

	@Column(name = "narration", nullable = false, length = 65535)
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
