package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemorandumTransactionsrow generated by hbm2java
 */
@Entity
@Table(name = "memorandum_transactionsrow")
public class MemorandumTransactionsrow implements java.io.Serializable {

	private Integer id;
	private int memorandumTransactionId;
	private Integer accountId;
	private String tax;
	private BigDecimal taxAmount;
	private BigDecimal taxPercentage;
	private String taxNarration;
	private BigDecimal amountCr;
	private BigDecimal amountDr;
	private Date createdAt;
	private String taxExcludedAmount;

	public MemorandumTransactionsrow() {
	}

	public MemorandumTransactionsrow(int memorandumTransactionId) {
		this.memorandumTransactionId = memorandumTransactionId;
	}

	public MemorandumTransactionsrow(int memorandumTransactionId, Integer accountId, String tax, BigDecimal taxAmount,
			BigDecimal taxPercentage, String taxNarration, BigDecimal amountCr, BigDecimal amountDr, Date createdAt,
			String taxExcludedAmount) {
		this.memorandumTransactionId = memorandumTransactionId;
		this.accountId = accountId;
		this.tax = tax;
		this.taxAmount = taxAmount;
		this.taxPercentage = taxPercentage;
		this.taxNarration = taxNarration;
		this.amountCr = amountCr;
		this.amountDr = amountDr;
		this.createdAt = createdAt;
		this.taxExcludedAmount = taxExcludedAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "memorandum_transaction_id", nullable = false)
	public int getMemorandumTransactionId() {
		return this.memorandumTransactionId;
	}

	public void setMemorandumTransactionId(int memorandumTransactionId) {
		this.memorandumTransactionId = memorandumTransactionId;
	}

	@Column(name = "account_id")
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@Column(name = "tax")
	public String getTax() {
		return this.tax;
	}

	public void setTax(String tax) {
		this.tax = tax;
	}

	@Column(name = "tax_amount", precision = 8)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "tax_percentage", precision = 8)
	public BigDecimal getTaxPercentage() {
		return this.taxPercentage;
	}

	public void setTaxPercentage(BigDecimal taxPercentage) {
		this.taxPercentage = taxPercentage;
	}

	@Column(name = "tax_narration", length = 65535)
	public String getTaxNarration() {
		return this.taxNarration;
	}

	public void setTaxNarration(String taxNarration) {
		this.taxNarration = taxNarration;
	}

	@Column(name = "amountCr", precision = 8)
	public BigDecimal getAmountCr() {
		return this.amountCr;
	}

	public void setAmountCr(BigDecimal amountCr) {
		this.amountCr = amountCr;
	}

	@Column(name = "amountDr", precision = 8)
	public BigDecimal getAmountDr() {
		return this.amountDr;
	}

	public void setAmountDr(BigDecimal amountDr) {
		this.amountDr = amountDr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "tax_excluded_amount", length = 65535)
	public String getTaxExcludedAmount() {
		return this.taxExcludedAmount;
	}

	public void setTaxExcludedAmount(String taxExcludedAmount) {
		this.taxExcludedAmount = taxExcludedAmount;
	}

}
