package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mos generated by hbm2java
 */
@Entity
@Table(name = "mos")
public class Mos implements java.io.Serializable {

	private Integer id;
	private Branches branches;
	private String name;
	private Byte isActive;
	private Set moAccountAssociations = new HashSet(0);

	public Mos() {
	}

	public Mos(Branches branches, String name, Byte isActive, Set moAccountAssociations) {
		this.branches = branches;
		this.name = name;
		this.isActive = isActive;
		this.moAccountAssociations = moAccountAssociations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_active")
	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mos")
	public Set<MoAccountAssociation> getMoAccountAssociations() {
		return this.moAccountAssociations;
	}

	public void setMoAccountAssociations(Set moAccountAssociations) {
		this.moAccountAssociations = moAccountAssociations;
	}

}
