package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Noclog generated by hbm2java
 */
@Entity
@Table(name = "noclog")
public class Noclog implements java.io.Serializable {

	private Integer id;
	private int accountsId;
	private int createdById;
	private int fromBranchId;
	private Integer toBranchId;
	private Integer receivedById;
	private int returnReceivedById;
	private Date nocLetterReceivedOn;
	private Date sendAt;
	private String sendNarration;
	private Date receivedAt;
	private String receivedNarration;
	private int isDispatchToCustomer;
	private String dispatchNarration;
	private Date dispatchAt;
	private int isReturn;
	private Date returnAt;
	private String returnReceivedNarration;
	private int dispatchById;
	private String returnNarration;
	private int returnById;
	private byte isNocNotMade;
	private String nocNotMadeDueTo;
	private byte isNocHold;
	private String nocHoldDueTo;

	public Noclog() {
	}

	public Noclog(int accountsId, int createdById, int fromBranchId, int returnReceivedById, Date sendAt,
			Date receivedAt, String receivedNarration, int isDispatchToCustomer, Date dispatchAt, int isReturn,
			Date returnAt, int dispatchById, String returnNarration, int returnById, byte isNocNotMade,
			String nocNotMadeDueTo, byte isNocHold, String nocHoldDueTo) {
		this.accountsId = accountsId;
		this.createdById = createdById;
		this.fromBranchId = fromBranchId;
		this.returnReceivedById = returnReceivedById;
		this.sendAt = sendAt;
		this.receivedAt = receivedAt;
		this.receivedNarration = receivedNarration;
		this.isDispatchToCustomer = isDispatchToCustomer;
		this.dispatchAt = dispatchAt;
		this.isReturn = isReturn;
		this.returnAt = returnAt;
		this.dispatchById = dispatchById;
		this.returnNarration = returnNarration;
		this.returnById = returnById;
		this.isNocNotMade = isNocNotMade;
		this.nocNotMadeDueTo = nocNotMadeDueTo;
		this.isNocHold = isNocHold;
		this.nocHoldDueTo = nocHoldDueTo;
	}

	public Noclog(int accountsId, int createdById, int fromBranchId, Integer toBranchId, Integer receivedById,
			int returnReceivedById, Date nocLetterReceivedOn, Date sendAt, String sendNarration, Date receivedAt,
			String receivedNarration, int isDispatchToCustomer, String dispatchNarration, Date dispatchAt, int isReturn,
			Date returnAt, String returnReceivedNarration, int dispatchById, String returnNarration, int returnById,
			byte isNocNotMade, String nocNotMadeDueTo, byte isNocHold, String nocHoldDueTo) {
		this.accountsId = accountsId;
		this.createdById = createdById;
		this.fromBranchId = fromBranchId;
		this.toBranchId = toBranchId;
		this.receivedById = receivedById;
		this.returnReceivedById = returnReceivedById;
		this.nocLetterReceivedOn = nocLetterReceivedOn;
		this.sendAt = sendAt;
		this.sendNarration = sendNarration;
		this.receivedAt = receivedAt;
		this.receivedNarration = receivedNarration;
		this.isDispatchToCustomer = isDispatchToCustomer;
		this.dispatchNarration = dispatchNarration;
		this.dispatchAt = dispatchAt;
		this.isReturn = isReturn;
		this.returnAt = returnAt;
		this.returnReceivedNarration = returnReceivedNarration;
		this.dispatchById = dispatchById;
		this.returnNarration = returnNarration;
		this.returnById = returnById;
		this.isNocNotMade = isNocNotMade;
		this.nocNotMadeDueTo = nocNotMadeDueTo;
		this.isNocHold = isNocHold;
		this.nocHoldDueTo = nocHoldDueTo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "accounts_id", nullable = false)
	public int getAccountsId() {
		return this.accountsId;
	}

	public void setAccountsId(int accountsId) {
		this.accountsId = accountsId;
	}

	@Column(name = "created_by_id", nullable = false)
	public int getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(int createdById) {
		this.createdById = createdById;
	}

	@Column(name = "from_branch_id", nullable = false)
	public int getFromBranchId() {
		return this.fromBranchId;
	}

	public void setFromBranchId(int fromBranchId) {
		this.fromBranchId = fromBranchId;
	}

	@Column(name = "to_branch_id")
	public Integer getToBranchId() {
		return this.toBranchId;
	}

	public void setToBranchId(Integer toBranchId) {
		this.toBranchId = toBranchId;
	}

	@Column(name = "received_by_id")
	public Integer getReceivedById() {
		return this.receivedById;
	}

	public void setReceivedById(Integer receivedById) {
		this.receivedById = receivedById;
	}

	@Column(name = "return_received_by_id", nullable = false)
	public int getReturnReceivedById() {
		return this.returnReceivedById;
	}

	public void setReturnReceivedById(int returnReceivedById) {
		this.returnReceivedById = returnReceivedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "noc_letter_received_on", length = 19)
	public Date getNocLetterReceivedOn() {
		return this.nocLetterReceivedOn;
	}

	public void setNocLetterReceivedOn(Date nocLetterReceivedOn) {
		this.nocLetterReceivedOn = nocLetterReceivedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_at", nullable = false, length = 19)
	public Date getSendAt() {
		return this.sendAt;
	}

	public void setSendAt(Date sendAt) {
		this.sendAt = sendAt;
	}

	@Column(name = "send_narration", length = 65535)
	public String getSendNarration() {
		return this.sendNarration;
	}

	public void setSendNarration(String sendNarration) {
		this.sendNarration = sendNarration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "received_at", nullable = false, length = 19)
	public Date getReceivedAt() {
		return this.receivedAt;
	}

	public void setReceivedAt(Date receivedAt) {
		this.receivedAt = receivedAt;
	}

	@Column(name = "received_narration", nullable = false, length = 65535)
	public String getReceivedNarration() {
		return this.receivedNarration;
	}

	public void setReceivedNarration(String receivedNarration) {
		this.receivedNarration = receivedNarration;
	}

	@Column(name = "is_dispatch_to_customer", nullable = false)
	public int getIsDispatchToCustomer() {
		return this.isDispatchToCustomer;
	}

	public void setIsDispatchToCustomer(int isDispatchToCustomer) {
		this.isDispatchToCustomer = isDispatchToCustomer;
	}

	@Column(name = "dispatch_narration", length = 65535)
	public String getDispatchNarration() {
		return this.dispatchNarration;
	}

	public void setDispatchNarration(String dispatchNarration) {
		this.dispatchNarration = dispatchNarration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dispatch_at", nullable = false, length = 19)
	public Date getDispatchAt() {
		return this.dispatchAt;
	}

	public void setDispatchAt(Date dispatchAt) {
		this.dispatchAt = dispatchAt;
	}

	@Column(name = "is_return", nullable = false)
	public int getIsReturn() {
		return this.isReturn;
	}

	public void setIsReturn(int isReturn) {
		this.isReturn = isReturn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "return_at", nullable = false, length = 19)
	public Date getReturnAt() {
		return this.returnAt;
	}

	public void setReturnAt(Date returnAt) {
		this.returnAt = returnAt;
	}

	@Column(name = "return_received_narration", length = 65535)
	public String getReturnReceivedNarration() {
		return this.returnReceivedNarration;
	}

	public void setReturnReceivedNarration(String returnReceivedNarration) {
		this.returnReceivedNarration = returnReceivedNarration;
	}

	@Column(name = "dispatch_by_id", nullable = false)
	public int getDispatchById() {
		return this.dispatchById;
	}

	public void setDispatchById(int dispatchById) {
		this.dispatchById = dispatchById;
	}

	@Column(name = "return_narration", nullable = false, length = 65535)
	public String getReturnNarration() {
		return this.returnNarration;
	}

	public void setReturnNarration(String returnNarration) {
		this.returnNarration = returnNarration;
	}

	@Column(name = "return_by_id", nullable = false)
	public int getReturnById() {
		return this.returnById;
	}

	public void setReturnById(int returnById) {
		this.returnById = returnById;
	}

	@Column(name = "is_noc_not_made", nullable = false)
	public byte getIsNocNotMade() {
		return this.isNocNotMade;
	}

	public void setIsNocNotMade(byte isNocNotMade) {
		this.isNocNotMade = isNocNotMade;
	}

	@Column(name = "noc_not_made_due_to", nullable = false, length = 65535)
	public String getNocNotMadeDueTo() {
		return this.nocNotMadeDueTo;
	}

	public void setNocNotMadeDueTo(String nocNotMadeDueTo) {
		this.nocNotMadeDueTo = nocNotMadeDueTo;
	}

	@Column(name = "is_noc_hold", nullable = false)
	public byte getIsNocHold() {
		return this.isNocHold;
	}

	public void setIsNocHold(byte isNocHold) {
		this.isNocHold = isNocHold;
	}

	@Column(name = "noc_hold_due_to", nullable = false, length = 65535)
	public String getNocHoldDueTo() {
		return this.nocHoldDueTo;
	}

	public void setNocHoldDueTo(String nocHoldDueTo) {
		this.nocHoldDueTo = nocHoldDueTo;
	}

}
