package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Premiums generated by hbm2java
 */
@Entity
@Table(name = "premiums")
public class Premiums implements java.io.Serializable {

	private Integer id;
	private Integer accountId;
	private String amount;
	private Boolean paid;
	private Boolean skipped;
	private Date createdAt;
	private Date updatedAt;
	private Date paidOn;
	private Boolean agentCommissionSend;
	private Double agentCommissionPercentage;
	private BigDecimal agentCollectionChargesPercentage;
	private Date dueDate;
	private BigDecimal paneltyCharged;
	private BigDecimal paneltyPosted;
	private Boolean agentCollectionChargesSend;

	public Premiums() {
	}

	public Premiums(Integer accountId, String amount, Boolean paid, Boolean skipped, Date createdAt, Date updatedAt,
			Date paidOn, Boolean agentCommissionSend, Double agentCommissionPercentage,
			BigDecimal agentCollectionChargesPercentage, Date dueDate, BigDecimal paneltyCharged,
			BigDecimal paneltyPosted, Boolean agentCollectionChargesSend) {
		this.accountId = accountId;
		this.amount = amount;
		this.paid = paid;
		this.skipped = skipped;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.paidOn = paidOn;
		this.agentCommissionSend = agentCommissionSend;
		this.agentCommissionPercentage = agentCommissionPercentage;
		this.agentCollectionChargesPercentage = agentCollectionChargesPercentage;
		this.dueDate = dueDate;
		this.paneltyCharged = paneltyCharged;
		this.paneltyPosted = paneltyPosted;
		this.agentCollectionChargesSend = agentCollectionChargesSend;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account_id")
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@Column(name = "Amount", length = 45)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Column(name = "Paid")
	public Boolean getPaid() {
		return this.paid;
	}

	public void setPaid(Boolean paid) {
		this.paid = paid;
	}

	@Column(name = "Skipped")
	public Boolean getSkipped() {
		return this.skipped;
	}

	public void setSkipped(Boolean skipped) {
		this.skipped = skipped;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PaidOn", length = 19)
	public Date getPaidOn() {
		return this.paidOn;
	}

	public void setPaidOn(Date paidOn) {
		this.paidOn = paidOn;
	}

	@Column(name = "AgentCommissionSend")
	public Boolean getAgentCommissionSend() {
		return this.agentCommissionSend;
	}

	public void setAgentCommissionSend(Boolean agentCommissionSend) {
		this.agentCommissionSend = agentCommissionSend;
	}

	@Column(name = "AgentCommissionPercentage", precision = 22, scale = 0)
	public Double getAgentCommissionPercentage() {
		return this.agentCommissionPercentage;
	}

	public void setAgentCommissionPercentage(Double agentCommissionPercentage) {
		this.agentCommissionPercentage = agentCommissionPercentage;
	}

	@Column(name = "AgentCollectionChargesPercentage", precision = 10)
	public BigDecimal getAgentCollectionChargesPercentage() {
		return this.agentCollectionChargesPercentage;
	}

	public void setAgentCollectionChargesPercentage(BigDecimal agentCollectionChargesPercentage) {
		this.agentCollectionChargesPercentage = agentCollectionChargesPercentage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DueDate", length = 19)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "PaneltyCharged", precision = 10)
	public BigDecimal getPaneltyCharged() {
		return this.paneltyCharged;
	}

	public void setPaneltyCharged(BigDecimal paneltyCharged) {
		this.paneltyCharged = paneltyCharged;
	}

	@Column(name = "PaneltyPosted", precision = 10)
	public BigDecimal getPaneltyPosted() {
		return this.paneltyPosted;
	}

	public void setPaneltyPosted(BigDecimal paneltyPosted) {
		this.paneltyPosted = paneltyPosted;
	}

	@Column(name = "AgentCollectionChargesSend")
	public Boolean getAgentCollectionChargesSend() {
		return this.agentCollectionChargesSend;
	}

	public void setAgentCollectionChargesSend(Boolean agentCollectionChargesSend) {
		this.agentCollectionChargesSend = agentCollectionChargesSend;
	}

}
