package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShareCertificate generated by hbm2java
 */
@Entity
@Table(name = "share_certificate")
public class ShareCertificate implements java.io.Serializable {

	private Integer id;
	private Integer name;
	private String issued;
	private String status;
	private Date createdAt;
	private Date submittedAt;

	public ShareCertificate() {
	}

	public ShareCertificate(Integer name, String issued, String status, Date createdAt, Date submittedAt) {
		this.name = name;
		this.issued = issued;
		this.status = status;
		this.createdAt = createdAt;
		this.submittedAt = submittedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public Integer getName() {
		return this.name;
	}

	public void setName(Integer name) {
		this.name = name;
	}

	@Column(name = "Issued")
	public String getIssued() {
		return this.issued;
	}

	public void setIssued(String issued) {
		this.issued = issued;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "submitted_at", length = 19)
	public Date getSubmittedAt() {
		return this.submittedAt;
	}

	public void setSubmittedAt(Date submittedAt) {
		this.submittedAt = submittedAt;
	}

}
