package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicUpdate;

/**
 * ShareHistory generated by hbm2java
 */
@Entity
@Table(name = "share_history")
public class ShareHistory implements java.io.Serializable {

	private Integer id;
	private Integer memberId;
	private Integer shareId;
	private Date fromDate;
	private Date finalToDate;
	private Integer shareCertificateId;

	public ShareHistory() {
	}

	public ShareHistory(Integer memberId, Integer shareId, Date fromDate, Date finalToDate,
			Integer shareCertificateId) {
		this.memberId = memberId;
		this.shareId = shareId;
		this.fromDate = fromDate;
		this.finalToDate = finalToDate;
		this.shareCertificateId = shareCertificateId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "member_id")
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@Column(name = "share_id")
	public Integer getShareId() {
		return this.shareId;
	}

	public void setShareId(Integer shareId) {
		this.shareId = shareId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "from_date", length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "final_to_date", length = 19)
	public Date getFinalToDate() {
		return this.finalToDate;
	}

	public void setFinalToDate(Date finalToDate) {
		this.finalToDate = finalToDate;
	}

	@Column(name = "share_certificate_id")
	public Integer getShareCertificateId() {
		return this.shareCertificateId;
	}

	public void setShareCertificateId(Integer shareCertificateId) {
		this.shareCertificateId = shareCertificateId;
	}

	@Override
	public String toString() {
		return "ShareHistory [id=" + id + ", memberId=" + memberId + ", shareId=" + shareId + ", fromDate=" + fromDate
				+ ", finalToDate=" + finalToDate + ", shareCertificateId=" + shareCertificateId + "]";
	}
	
	

}
