package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Share generated by hbm2java
 */
@Entity
@Table(name = "share", uniqueConstraints = @UniqueConstraint(columnNames = "no"))
public class Share implements java.io.Serializable {

	private Integer id;
	private Integer currentMemberId;
	private Integer no;
	private String status;
	private String buybackLockingMonths;
	private String transferLockingMonths;
	private Integer shareCertificateId;

	public Share() {
	}

	public Share(Integer currentMemberId, Integer no, String status, String buybackLockingMonths,
			String transferLockingMonths, Integer shareCertificateId) {
		this.currentMemberId = currentMemberId;
		this.no = no;
		this.status = status;
		this.buybackLockingMonths = buybackLockingMonths;
		this.transferLockingMonths = transferLockingMonths;
		this.shareCertificateId = shareCertificateId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "current_member_id")
	public Integer getCurrentMemberId() {
		return this.currentMemberId;
	}

	public void setCurrentMemberId(Integer currentMemberId) {
		this.currentMemberId = currentMemberId;
	}

	@Column(name = "no", unique = true)
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "buyback_locking_months")
	public String getBuybackLockingMonths() {
		return this.buybackLockingMonths;
	}

	public void setBuybackLockingMonths(String buybackLockingMonths) {
		this.buybackLockingMonths = buybackLockingMonths;
	}

	@Column(name = "transfer_locking_months")
	public String getTransferLockingMonths() {
		return this.transferLockingMonths;
	}

	public void setTransferLockingMonths(String transferLockingMonths) {
		this.transferLockingMonths = transferLockingMonths;
	}

	@Column(name = "share_certificate_id")
	public Integer getShareCertificateId() {
		return this.shareCertificateId;
	}

	public void setShareCertificateId(Integer shareCertificateId) {
		this.shareCertificateId = shareCertificateId;
	}

}
