package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Staffs generated by hbm2java
 */
@Entity
@Table(name = "staffs", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Staffs implements java.io.Serializable {

	private Integer id;
	private String username;
	private Integer branchId;
	private String accessLevel;
	private String name;
	private String fatherName;
	private String pfAmount;
	private String basicPay;
	private String variablePay;
	private String createdAt;
	private String presentAddress;
	private String parmanentAddress;
	private String mobileNo;
	private String landlineNo;
	private String dob;
	private String password;
	private String motherName;
	private Boolean isActive;
	private String marriatalStatus;
	private String bloodGroup;
	private String empCode;
	private String emergencyNo;
	private String panNo;
	private String role;
	private String lastQualification;
	private String designation;
	private String remark;
	private String amountOfIncrement;
	private String yearlyIncrementAmount;
	private String salary;
	private String relavingDateIfNotActive;
	private String securityAmount;
	private Date depositDate;
	private String totalDepAmount;
	private String postingAt;
	private String pfNo;
	private String bankName;
	private String ifscCode;
	private String accountNo;
	private String lastDateOfIncrement;
	private String nomineeName;
	private String nomineeAge;
	private String relationWithNominee;
	private Set aclses = new HashSet(0);
	private Set staffReportAcls = new HashSet(0);

	public Staffs() {
	}

	
	
	public Staffs(String username, Integer branchId, String accessLevel, String name, String fatherName,
			String pfAmount, String basicPay, String variablePay, String createdAt, String presentAddress,
			String parmanentAddress, String mobileNo, String landlineNo, String dob, String password, String motherName,
			Boolean isActive, String marriatalStatus, String bloodGroup, String empCode, String emergencyNo,
			String panNo, String role, String lastQualification, String designation, String remark,
			String amountOfIncrement, String yearlyIncrementAmount, String salary, String relavingDateIfNotActive,
			String securityAmount, Date depositDate, String totalDepAmount, String postingAt, String pfNo,
			String bankName, String ifscCode, String accountNo, String lastDateOfIncrement, String nomineeName,
			String nomineeAge, String relationWithNominee, Set aclses, Set staffReportAcls) {
		this.username = username;
		this.branchId = branchId;
		this.accessLevel = accessLevel;
		this.name = name;
		this.fatherName = fatherName;
		this.pfAmount = pfAmount;
		this.basicPay = basicPay;
		this.variablePay = variablePay;
		this.createdAt = createdAt;
		this.presentAddress = presentAddress;
		this.parmanentAddress = parmanentAddress;
		this.mobileNo = mobileNo;
		this.landlineNo = landlineNo;
		this.dob = dob;
		this.password = password;
		this.motherName = motherName;
		this.isActive = isActive;
		this.marriatalStatus = marriatalStatus;
		this.bloodGroup = bloodGroup;
		this.empCode = empCode;
		this.emergencyNo = emergencyNo;
		this.panNo = panNo;
		this.role = role;
		this.lastQualification = lastQualification;
		this.designation = designation;
		this.remark = remark;
		this.amountOfIncrement = amountOfIncrement;
		this.yearlyIncrementAmount = yearlyIncrementAmount;
		this.salary = salary;
		this.relavingDateIfNotActive = relavingDateIfNotActive;
		this.securityAmount = securityAmount;
		this.depositDate = depositDate;
		this.totalDepAmount = totalDepAmount;
		this.postingAt = postingAt;
		this.pfNo = pfNo;
		this.bankName = bankName;
		this.ifscCode = ifscCode;
		this.accountNo = accountNo;
		this.lastDateOfIncrement = lastDateOfIncrement;
		this.nomineeName = nomineeName;
		this.nomineeAge = nomineeAge;
		this.relationWithNominee = relationWithNominee;
		this.aclses = aclses;
		this.staffReportAcls = staffReportAcls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", unique = true)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "branch_id")
	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	@Column(name = "AccessLevel")
	public String getAccessLevel() {
		return this.accessLevel;
	}

	public void setAccessLevel(String accessLevel) {
		this.accessLevel = accessLevel;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "father_name")
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "pf_amount")
	public String getPfAmount() {
		return this.pfAmount;
	}

	public void setPfAmount(String pfAmount) {
		this.pfAmount = pfAmount;
	}

	@Column(name = "basic_pay")
	public String getBasicPay() {
		return this.basicPay;
	}

	public void setBasicPay(String basicPay) {
		this.basicPay = basicPay;
	}

	@Column(name = "variable_pay")
	public String getVariablePay() {
		return this.variablePay;
	}

	public void setVariablePay(String variablePay) {
		this.variablePay = variablePay;
	}

	@Column(name = "created_at")
	public String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "present_address", length = 65535)
	public String getPresentAddress() {
		return this.presentAddress;
	}

	public void setPresentAddress(String presentAddress) {
		this.presentAddress = presentAddress;
	}

	@Column(name = "parmanent_address", length = 65535)
	public String getParmanentAddress() {
		return this.parmanentAddress;
	}

	public void setParmanentAddress(String parmanentAddress) {
		this.parmanentAddress = parmanentAddress;
	}

	@Column(name = "mobile_no")
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "landline_no")
	public String getLandlineNo() {
		return this.landlineNo;
	}

	public void setLandlineNo(String landlineNo) {
		this.landlineNo = landlineNo;
	}

	@Column(name = "DOB")
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mother_name")
	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "marriatal_status")
	public String getMarriatalStatus() {
		return this.marriatalStatus;
	}

	public void setMarriatalStatus(String marriatalStatus) {
		this.marriatalStatus = marriatalStatus;
	}

	@Column(name = "blood_group")
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name = "emp_code")
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Column(name = "emergency_no")
	public String getEmergencyNo() {
		return this.emergencyNo;
	}

	public void setEmergencyNo(String emergencyNo) {
		this.emergencyNo = emergencyNo;
	}

	@Column(name = "pan_no")
	public String getPanNo() {
		return this.panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	@Column(name = "role")
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "last_qualification")
	public String getLastQualification() {
		return this.lastQualification;
	}

	public void setLastQualification(String lastQualification) {
		this.lastQualification = lastQualification;
	}

	@Column(name = "designation")
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "remark", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "amount_of_increment")
	public String getAmountOfIncrement() {
		return this.amountOfIncrement;
	}

	public void setAmountOfIncrement(String amountOfIncrement) {
		this.amountOfIncrement = amountOfIncrement;
	}

	@Column(name = "yearly_increment_amount")
	public String getYearlyIncrementAmount() {
		return this.yearlyIncrementAmount;
	}

	public void setYearlyIncrementAmount(String yearlyIncrementAmount) {
		this.yearlyIncrementAmount = yearlyIncrementAmount;
	}

	@Column(name = "salary")
	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	@Column(name = "relaving_date_if_not_active")
	public String getRelavingDateIfNotActive() {
		return this.relavingDateIfNotActive;
	}

	public void setRelavingDateIfNotActive(String relavingDateIfNotActive) {
		this.relavingDateIfNotActive = relavingDateIfNotActive;
	}

	@Column(name = "security_amount")
	public String getSecurityAmount() {
		return this.securityAmount;
	}

	public void setSecurityAmount(String securityAmount) {
		this.securityAmount = securityAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deposit_date", length = 10)
	public Date getDepositDate() {
		return this.depositDate;
	}

	public void setDepositDate(Date depositDate) {
		this.depositDate = depositDate;
	}

	@Column(name = "total_dep_amount")
	public String getTotalDepAmount() {
		return this.totalDepAmount;
	}

	public void setTotalDepAmount(String totalDepAmount) {
		this.totalDepAmount = totalDepAmount;
	}

	@Column(name = "posting_at")
	public String getPostingAt() {
		return this.postingAt;
	}

	public void setPostingAt(String postingAt) {
		this.postingAt = postingAt;
	}

	@Column(name = "pf_no")
	public String getPfNo() {
		return this.pfNo;
	}

	public void setPfNo(String pfNo) {
		this.pfNo = pfNo;
	}

	@Column(name = "bank_name")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "ifsc_code")
	public String getIfscCode() {
		return this.ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

	@Column(name = "account_no")
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "last_date_of_increment")
	public String getLastDateOfIncrement() {
		return this.lastDateOfIncrement;
	}

	public void setLastDateOfIncrement(String lastDateOfIncrement) {
		this.lastDateOfIncrement = lastDateOfIncrement;
	}

	@Column(name = "nominee_name")
	public String getNomineeName() {
		return this.nomineeName;
	}

	public void setNomineeName(String nomineeName) {
		this.nomineeName = nomineeName;
	}

	@Column(name = "nominee_age")
	public String getNomineeAge() {
		return this.nomineeAge;
	}

	public void setNomineeAge(String nomineeAge) {
		this.nomineeAge = nomineeAge;
	}

	@Column(name = "relation_with_nominee")
	public String getRelationWithNominee() {
		return this.relationWithNominee;
	}

	public void setRelationWithNominee(String relationWithNominee) {
		this.relationWithNominee = relationWithNominee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staffs")
	public Set<Acls> getAclses() {
		return this.aclses;
	}

	public void setAclses(Set aclses) {
		this.aclses = aclses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staffs")
	public Set<StaffReportAcl> getStaffReportAcls() {
		return this.staffReportAcls;
	}

	public void setStaffReportAcls(Set staffReportAcls) {
		this.staffReportAcls = staffReportAcls;
	}

}
