package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StockMembers generated by hbm2java
 */
@Entity
@Table(name = "stock_members")
public class StockMembers implements java.io.Serializable {

	private Integer id;
	private Branches branches;
	private String name;
	private String address;
	private String phNo;
	private String type;
	private Boolean isActive;
	private Set stockTransactionses = new HashSet(0);

	public StockMembers() {
	}

	public StockMembers(Branches branches, String name, String address, String phNo, String type, Boolean isActive,
			Set stockTransactionses) {
		this.branches = branches;
		this.name = name;
		this.address = address;
		this.phNo = phNo;
		this.type = type;
		this.isActive = isActive;
		this.stockTransactionses = stockTransactionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "ph_no")
	public String getPhNo() {
		return this.phNo;
	}

	public void setPhNo(String phNo) {
		this.phNo = phNo;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockMembers")
	public Set<StockTransactions> getStockTransactionses() {
		return this.stockTransactionses;
	}

	public void setStockTransactionses(Set stockTransactionses) {
		this.stockTransactionses = stockTransactionses;
	}

}
