package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StocknewContainerrow generated by hbm2java
 */
@Entity
@Table(name = "stocknew_containerrow")
public class StocknewContainerrow implements java.io.Serializable {

	private Integer id;
	private StocknewContainer stocknewContainer;
	private String name;
	private Boolean isDefault;
	private Set stocknewTransactionsesForFromContainerRowId = new HashSet(0);
	private Set stocknewTransactionsesForToContainerRowId = new HashSet(0);

	public StocknewContainerrow() {
	}

	public StocknewContainerrow(StocknewContainer stocknewContainer, String name, Boolean isDefault,
			Set stocknewTransactionsesForFromContainerRowId, Set stocknewTransactionsesForToContainerRowId) {
		this.stocknewContainer = stocknewContainer;
		this.name = name;
		this.isDefault = isDefault;
		this.stocknewTransactionsesForFromContainerRowId = stocknewTransactionsesForFromContainerRowId;
		this.stocknewTransactionsesForToContainerRowId = stocknewTransactionsesForToContainerRowId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "container_id")
	public StocknewContainer getStocknewContainer() {
		return this.stocknewContainer;
	}

	public void setStocknewContainer(StocknewContainer stocknewContainer) {
		this.stocknewContainer = stocknewContainer;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_default")
	public Boolean getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stocknewContainerrowByFromContainerRowId")
	public Set<StocknewTransactions> getStocknewTransactionsesForFromContainerRowId() {
		return this.stocknewTransactionsesForFromContainerRowId;
	}

	public void setStocknewTransactionsesForFromContainerRowId(Set stocknewTransactionsesForFromContainerRowId) {
		this.stocknewTransactionsesForFromContainerRowId = stocknewTransactionsesForFromContainerRowId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stocknewContainerrowByToContainerRowId")
	public Set<StocknewTransactions> getStocknewTransactionsesForToContainerRowId() {
		return this.stocknewTransactionsesForToContainerRowId;
	}

	public void setStocknewTransactionsesForToContainerRowId(Set stocknewTransactionsesForToContainerRowId) {
		this.stocknewTransactionsesForToContainerRowId = stocknewTransactionsesForToContainerRowId;
	}

}
