package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StockContainers generated by hbm2java
 */
@Entity
@Table(name = "stock_containers")
public class StockContainers implements java.io.Serializable {

	private Integer id;
	private Branches branches;
	private String name;
	private Set stockContainerrowitemqties = new HashSet(0);
	private Set stockTransactionsesForToContainerId = new HashSet(0);
	private Set stockRowses = new HashSet(0);
	private Set stockTransactionsesForFromContainerId = new HashSet(0);

	public StockContainers() {
	}

	public StockContainers(Branches branches, String name, Set stockContainerrowitemqties,
			Set stockTransactionsesForToContainerId, Set stockRowses, Set stockTransactionsesForFromContainerId) {
		this.branches = branches;
		this.name = name;
		this.stockContainerrowitemqties = stockContainerrowitemqties;
		this.stockTransactionsesForToContainerId = stockTransactionsesForToContainerId;
		this.stockRowses = stockRowses;
		this.stockTransactionsesForFromContainerId = stockTransactionsesForFromContainerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockContainers")
	public Set<StockContainerrowitemqty> getStockContainerrowitemqties() {
		return this.stockContainerrowitemqties;
	}

	public void setStockContainerrowitemqties(Set stockContainerrowitemqties) {
		this.stockContainerrowitemqties = stockContainerrowitemqties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockContainersByToContainerId")
	public Set<StockTransactions> getStockTransactionsesForToContainerId() {
		return this.stockTransactionsesForToContainerId;
	}

	public void setStockTransactionsesForToContainerId(Set stockTransactionsesForToContainerId) {
		this.stockTransactionsesForToContainerId = stockTransactionsesForToContainerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockContainers")
	public Set<StockRows> getStockRowses() {
		return this.stockRowses;
	}

	public void setStockRowses(Set stockRowses) {
		this.stockRowses = stockRowses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockContainersByFromContainerId")
	public Set<StockTransactions> getStockTransactionsesForFromContainerId() {
		return this.stockTransactionsesForFromContainerId;
	}

	public void setStockTransactionsesForFromContainerId(Set stockTransactionsesForFromContainerId) {
		this.stockTransactionsesForFromContainerId = stockTransactionsesForFromContainerId;
	}

}
