package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StocknewTransactions generated by hbm2java
 */
@Entity
@Table(name = "stocknew_transactions")
public class StocknewTransactions implements java.io.Serializable {

	private Integer id;
	private Branches branchesByFromBranchId;
	private Branches branchesByToBranchId;
	private StocknewContainer stocknewContainerByFromContainerId;
	private StocknewContainer stocknewContainerByToContainerId;
	private StocknewContainerrow stocknewContainerrowByFromContainerRowId;
	private StocknewContainerrow stocknewContainerrowByToContainerRowId;
	private StocknewItems stocknewItems;
	private StocknewMembers stocknewMembersByFromMemberId;
	private StocknewMembers stocknewMembersByToMemberId;
	private StocknewTransactiontemplate stocknewTransactiontemplate;
	private String qty;
	private BigDecimal rate;
	private String narration;
	private String createdAt;

	public StocknewTransactions() {
	}

	public StocknewTransactions(Branches branchesByFromBranchId, Branches branchesByToBranchId,
			StocknewContainer stocknewContainerByFromContainerId, StocknewContainer stocknewContainerByToContainerId,
			StocknewContainerrow stocknewContainerrowByFromContainerRowId,
			StocknewContainerrow stocknewContainerrowByToContainerRowId, StocknewItems stocknewItems,
			StocknewMembers stocknewMembersByFromMemberId, StocknewMembers stocknewMembersByToMemberId,
			StocknewTransactiontemplate stocknewTransactiontemplate, String qty, BigDecimal rate, String narration,
			String createdAt) {
		this.branchesByFromBranchId = branchesByFromBranchId;
		this.branchesByToBranchId = branchesByToBranchId;
		this.stocknewContainerByFromContainerId = stocknewContainerByFromContainerId;
		this.stocknewContainerByToContainerId = stocknewContainerByToContainerId;
		this.stocknewContainerrowByFromContainerRowId = stocknewContainerrowByFromContainerRowId;
		this.stocknewContainerrowByToContainerRowId = stocknewContainerrowByToContainerRowId;
		this.stocknewItems = stocknewItems;
		this.stocknewMembersByFromMemberId = stocknewMembersByFromMemberId;
		this.stocknewMembersByToMemberId = stocknewMembersByToMemberId;
		this.stocknewTransactiontemplate = stocknewTransactiontemplate;
		this.qty = qty;
		this.rate = rate;
		this.narration = narration;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_branch_id")
	public Branches getBranchesByFromBranchId() {
		return this.branchesByFromBranchId;
	}

	public void setBranchesByFromBranchId(Branches branchesByFromBranchId) {
		this.branchesByFromBranchId = branchesByFromBranchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_branch_id")
	public Branches getBranchesByToBranchId() {
		return this.branchesByToBranchId;
	}

	public void setBranchesByToBranchId(Branches branchesByToBranchId) {
		this.branchesByToBranchId = branchesByToBranchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_container_id")
	public StocknewContainer getStocknewContainerByFromContainerId() {
		return this.stocknewContainerByFromContainerId;
	}

	public void setStocknewContainerByFromContainerId(StocknewContainer stocknewContainerByFromContainerId) {
		this.stocknewContainerByFromContainerId = stocknewContainerByFromContainerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_container_id")
	public StocknewContainer getStocknewContainerByToContainerId() {
		return this.stocknewContainerByToContainerId;
	}

	public void setStocknewContainerByToContainerId(StocknewContainer stocknewContainerByToContainerId) {
		this.stocknewContainerByToContainerId = stocknewContainerByToContainerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_container_row_id")
	public StocknewContainerrow getStocknewContainerrowByFromContainerRowId() {
		return this.stocknewContainerrowByFromContainerRowId;
	}

	public void setStocknewContainerrowByFromContainerRowId(
			StocknewContainerrow stocknewContainerrowByFromContainerRowId) {
		this.stocknewContainerrowByFromContainerRowId = stocknewContainerrowByFromContainerRowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_container_row_id")
	public StocknewContainerrow getStocknewContainerrowByToContainerRowId() {
		return this.stocknewContainerrowByToContainerRowId;
	}

	public void setStocknewContainerrowByToContainerRowId(StocknewContainerrow stocknewContainerrowByToContainerRowId) {
		this.stocknewContainerrowByToContainerRowId = stocknewContainerrowByToContainerRowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public StocknewItems getStocknewItems() {
		return this.stocknewItems;
	}

	public void setStocknewItems(StocknewItems stocknewItems) {
		this.stocknewItems = stocknewItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_member_id")
	public StocknewMembers getStocknewMembersByFromMemberId() {
		return this.stocknewMembersByFromMemberId;
	}

	public void setStocknewMembersByFromMemberId(StocknewMembers stocknewMembersByFromMemberId) {
		this.stocknewMembersByFromMemberId = stocknewMembersByFromMemberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_member_id")
	public StocknewMembers getStocknewMembersByToMemberId() {
		return this.stocknewMembersByToMemberId;
	}

	public void setStocknewMembersByToMemberId(StocknewMembers stocknewMembersByToMemberId) {
		this.stocknewMembersByToMemberId = stocknewMembersByToMemberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transaction_template_type_id")
	public StocknewTransactiontemplate getStocknewTransactiontemplate() {
		return this.stocknewTransactiontemplate;
	}

	public void setStocknewTransactiontemplate(StocknewTransactiontemplate stocknewTransactiontemplate) {
		this.stocknewTransactiontemplate = stocknewTransactiontemplate;
	}

	@Column(name = "qty")
	public String getQty() {
		return this.qty;
	}

	public void setQty(String qty) {
		this.qty = qty;
	}

	@Column(name = "rate", precision = 10)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Column(name = "narration", length = 65535)
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	@Column(name = "created_at")
	public String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

}
