package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockTransactions generated by hbm2java
 */
@Entity
@Table(name = "stock_transactions")
public class StockTransactions implements java.io.Serializable {

	private Integer id;
	private Branches branches;
	private StockContainers stockContainersByToContainerId;
	private StockContainers stockContainersByFromContainerId;
	private StockItems stockItems;
	private StockMembers stockMembers;
	private StockRows stockRowsByFromRowId;
	private StockRows stockRowsByToRowId;
	private String qty;
	private BigDecimal rate;
	private BigDecimal amount;
	private String narration;
	private Date createdAt;
	private String issueDate;
	private String submitDate;
	private String transactionType;
	private String toBranchId;
	private Boolean isUsedSubmit;

	public StockTransactions() {
	}

	public StockTransactions(Branches branches, StockContainers stockContainersByToContainerId,
			StockContainers stockContainersByFromContainerId, StockItems stockItems, StockMembers stockMembers,
			StockRows stockRowsByFromRowId, StockRows stockRowsByToRowId, String qty, BigDecimal rate,
			BigDecimal amount, String narration, Date createdAt, String issueDate, String submitDate,
			String transactionType, String toBranchId, Boolean isUsedSubmit) {
		this.branches = branches;
		this.stockContainersByToContainerId = stockContainersByToContainerId;
		this.stockContainersByFromContainerId = stockContainersByFromContainerId;
		this.stockItems = stockItems;
		this.stockMembers = stockMembers;
		this.stockRowsByFromRowId = stockRowsByFromRowId;
		this.stockRowsByToRowId = stockRowsByToRowId;
		this.qty = qty;
		this.rate = rate;
		this.amount = amount;
		this.narration = narration;
		this.createdAt = createdAt;
		this.issueDate = issueDate;
		this.submitDate = submitDate;
		this.transactionType = transactionType;
		this.toBranchId = toBranchId;
		this.isUsedSubmit = isUsedSubmit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_container_id")
	public StockContainers getStockContainersByToContainerId() {
		return this.stockContainersByToContainerId;
	}

	public void setStockContainersByToContainerId(StockContainers stockContainersByToContainerId) {
		this.stockContainersByToContainerId = stockContainersByToContainerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_container_id")
	public StockContainers getStockContainersByFromContainerId() {
		return this.stockContainersByFromContainerId;
	}

	public void setStockContainersByFromContainerId(StockContainers stockContainersByFromContainerId) {
		this.stockContainersByFromContainerId = stockContainersByFromContainerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public StockItems getStockItems() {
		return this.stockItems;
	}

	public void setStockItems(StockItems stockItems) {
		this.stockItems = stockItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public StockMembers getStockMembers() {
		return this.stockMembers;
	}

	public void setStockMembers(StockMembers stockMembers) {
		this.stockMembers = stockMembers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_row_id")
	public StockRows getStockRowsByFromRowId() {
		return this.stockRowsByFromRowId;
	}

	public void setStockRowsByFromRowId(StockRows stockRowsByFromRowId) {
		this.stockRowsByFromRowId = stockRowsByFromRowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_row_id")
	public StockRows getStockRowsByToRowId() {
		return this.stockRowsByToRowId;
	}

	public void setStockRowsByToRowId(StockRows stockRowsByToRowId) {
		this.stockRowsByToRowId = stockRowsByToRowId;
	}

	@Column(name = "qty")
	public String getQty() {
		return this.qty;
	}

	public void setQty(String qty) {
		this.qty = qty;
	}

	@Column(name = "rate", precision = 10)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "narration")
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "issue_date")
	public String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "submit_date")
	public String getSubmitDate() {
		return this.submitDate;
	}

	public void setSubmitDate(String submitDate) {
		this.submitDate = submitDate;
	}

	@Column(name = "transaction_type")
	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "to_branch_id")
	public String getToBranchId() {
		return this.toBranchId;
	}

	public void setToBranchId(String toBranchId) {
		this.toBranchId = toBranchId;
	}

	@Column(name = "is_used_submit")
	public Boolean getIsUsedSubmit() {
		return this.isUsedSubmit;
	}

	public void setIsUsedSubmit(Boolean isUsedSubmit) {
		this.isUsedSubmit = isUsedSubmit;
	}

}
