package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StocknewTransactiontemplate generated by hbm2java
 */
@Entity
@Table(name = "stocknew_transactiontemplate")
public class StocknewTransactiontemplate implements java.io.Serializable {

	private Integer id;
	private String name;
	private Boolean fromBranch;
	private Boolean fromSupplier;
	private Boolean fromStaff;
	private Boolean fromAgent;
	private Boolean fromDealer;
	private String itemCategories;
	private Boolean fromContainer;
	private Boolean fromContainerRow;
	private String fromContainerTypes;
	private Boolean toBranch;
	private Boolean toSupplier;
	private Boolean toStaff;
	private Boolean toAgent;
	private Boolean toDealer;
	private Boolean toContainer;
	private String toContainerTypes;
	private Boolean toContainerRow;
	private Boolean qty;
	private Boolean narration;
	private Boolean items;
	private Boolean rate;
	private Boolean alwaysFromCurrentBranch;
	private Boolean fromDefaultContainerRow;
	private Boolean alwaysToCurrentBranch;
	private Boolean toDefaultContainerRow;
	private Boolean checkFromQty;
	private Boolean subtractQtyFrom;
	private Boolean addQtyTo;
	private String allowedToAccesslevel;
	private Set stocknewTransactionses = new HashSet(0);

	public StocknewTransactiontemplate() {
	}

	public StocknewTransactiontemplate(String name, Boolean fromBranch, Boolean fromSupplier, Boolean fromStaff,
			Boolean fromAgent, Boolean fromDealer, String itemCategories, Boolean fromContainer,
			Boolean fromContainerRow, String fromContainerTypes, Boolean toBranch, Boolean toSupplier, Boolean toStaff,
			Boolean toAgent, Boolean toDealer, Boolean toContainer, String toContainerTypes, Boolean toContainerRow,
			Boolean qty, Boolean narration, Boolean items, Boolean rate, Boolean alwaysFromCurrentBranch,
			Boolean fromDefaultContainerRow, Boolean alwaysToCurrentBranch, Boolean toDefaultContainerRow,
			Boolean checkFromQty, Boolean subtractQtyFrom, Boolean addQtyTo, String allowedToAccesslevel,
			Set stocknewTransactionses) {
		this.name = name;
		this.fromBranch = fromBranch;
		this.fromSupplier = fromSupplier;
		this.fromStaff = fromStaff;
		this.fromAgent = fromAgent;
		this.fromDealer = fromDealer;
		this.itemCategories = itemCategories;
		this.fromContainer = fromContainer;
		this.fromContainerRow = fromContainerRow;
		this.fromContainerTypes = fromContainerTypes;
		this.toBranch = toBranch;
		this.toSupplier = toSupplier;
		this.toStaff = toStaff;
		this.toAgent = toAgent;
		this.toDealer = toDealer;
		this.toContainer = toContainer;
		this.toContainerTypes = toContainerTypes;
		this.toContainerRow = toContainerRow;
		this.qty = qty;
		this.narration = narration;
		this.items = items;
		this.rate = rate;
		this.alwaysFromCurrentBranch = alwaysFromCurrentBranch;
		this.fromDefaultContainerRow = fromDefaultContainerRow;
		this.alwaysToCurrentBranch = alwaysToCurrentBranch;
		this.toDefaultContainerRow = toDefaultContainerRow;
		this.checkFromQty = checkFromQty;
		this.subtractQtyFrom = subtractQtyFrom;
		this.addQtyTo = addQtyTo;
		this.allowedToAccesslevel = allowedToAccesslevel;
		this.stocknewTransactionses = stocknewTransactionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "from_branch")
	public Boolean getFromBranch() {
		return this.fromBranch;
	}

	public void setFromBranch(Boolean fromBranch) {
		this.fromBranch = fromBranch;
	}

	@Column(name = "from_supplier")
	public Boolean getFromSupplier() {
		return this.fromSupplier;
	}

	public void setFromSupplier(Boolean fromSupplier) {
		this.fromSupplier = fromSupplier;
	}

	@Column(name = "from_staff")
	public Boolean getFromStaff() {
		return this.fromStaff;
	}

	public void setFromStaff(Boolean fromStaff) {
		this.fromStaff = fromStaff;
	}

	@Column(name = "from_agent")
	public Boolean getFromAgent() {
		return this.fromAgent;
	}

	public void setFromAgent(Boolean fromAgent) {
		this.fromAgent = fromAgent;
	}

	@Column(name = "from_dealer")
	public Boolean getFromDealer() {
		return this.fromDealer;
	}

	public void setFromDealer(Boolean fromDealer) {
		this.fromDealer = fromDealer;
	}

	@Column(name = "item_categories")
	public String getItemCategories() {
		return this.itemCategories;
	}

	public void setItemCategories(String itemCategories) {
		this.itemCategories = itemCategories;
	}

	@Column(name = "from_container")
	public Boolean getFromContainer() {
		return this.fromContainer;
	}

	public void setFromContainer(Boolean fromContainer) {
		this.fromContainer = fromContainer;
	}

	@Column(name = "from_container_row")
	public Boolean getFromContainerRow() {
		return this.fromContainerRow;
	}

	public void setFromContainerRow(Boolean fromContainerRow) {
		this.fromContainerRow = fromContainerRow;
	}

	@Column(name = "from_container_types")
	public String getFromContainerTypes() {
		return this.fromContainerTypes;
	}

	public void setFromContainerTypes(String fromContainerTypes) {
		this.fromContainerTypes = fromContainerTypes;
	}

	@Column(name = "to_branch")
	public Boolean getToBranch() {
		return this.toBranch;
	}

	public void setToBranch(Boolean toBranch) {
		this.toBranch = toBranch;
	}

	@Column(name = "to_supplier")
	public Boolean getToSupplier() {
		return this.toSupplier;
	}

	public void setToSupplier(Boolean toSupplier) {
		this.toSupplier = toSupplier;
	}

	@Column(name = "to_staff")
	public Boolean getToStaff() {
		return this.toStaff;
	}

	public void setToStaff(Boolean toStaff) {
		this.toStaff = toStaff;
	}

	@Column(name = "to_agent")
	public Boolean getToAgent() {
		return this.toAgent;
	}

	public void setToAgent(Boolean toAgent) {
		this.toAgent = toAgent;
	}

	@Column(name = "to_dealer")
	public Boolean getToDealer() {
		return this.toDealer;
	}

	public void setToDealer(Boolean toDealer) {
		this.toDealer = toDealer;
	}

	@Column(name = "to_container")
	public Boolean getToContainer() {
		return this.toContainer;
	}

	public void setToContainer(Boolean toContainer) {
		this.toContainer = toContainer;
	}

	@Column(name = "to_container_types")
	public String getToContainerTypes() {
		return this.toContainerTypes;
	}

	public void setToContainerTypes(String toContainerTypes) {
		this.toContainerTypes = toContainerTypes;
	}

	@Column(name = "to_container_row")
	public Boolean getToContainerRow() {
		return this.toContainerRow;
	}

	public void setToContainerRow(Boolean toContainerRow) {
		this.toContainerRow = toContainerRow;
	}

	@Column(name = "qty")
	public Boolean getQty() {
		return this.qty;
	}

	public void setQty(Boolean qty) {
		this.qty = qty;
	}

	@Column(name = "narration")
	public Boolean getNarration() {
		return this.narration;
	}

	public void setNarration(Boolean narration) {
		this.narration = narration;
	}

	@Column(name = "items")
	public Boolean getItems() {
		return this.items;
	}

	public void setItems(Boolean items) {
		this.items = items;
	}

	@Column(name = "rate")
	public Boolean getRate() {
		return this.rate;
	}

	public void setRate(Boolean rate) {
		this.rate = rate;
	}

	@Column(name = "always_from_current_branch")
	public Boolean getAlwaysFromCurrentBranch() {
		return this.alwaysFromCurrentBranch;
	}

	public void setAlwaysFromCurrentBranch(Boolean alwaysFromCurrentBranch) {
		this.alwaysFromCurrentBranch = alwaysFromCurrentBranch;
	}

	@Column(name = "from_default_container_row")
	public Boolean getFromDefaultContainerRow() {
		return this.fromDefaultContainerRow;
	}

	public void setFromDefaultContainerRow(Boolean fromDefaultContainerRow) {
		this.fromDefaultContainerRow = fromDefaultContainerRow;
	}

	@Column(name = "always_to_current_branch")
	public Boolean getAlwaysToCurrentBranch() {
		return this.alwaysToCurrentBranch;
	}

	public void setAlwaysToCurrentBranch(Boolean alwaysToCurrentBranch) {
		this.alwaysToCurrentBranch = alwaysToCurrentBranch;
	}

	@Column(name = "to_default_container_row")
	public Boolean getToDefaultContainerRow() {
		return this.toDefaultContainerRow;
	}

	public void setToDefaultContainerRow(Boolean toDefaultContainerRow) {
		this.toDefaultContainerRow = toDefaultContainerRow;
	}

	@Column(name = "check_from_qty")
	public Boolean getCheckFromQty() {
		return this.checkFromQty;
	}

	public void setCheckFromQty(Boolean checkFromQty) {
		this.checkFromQty = checkFromQty;
	}

	@Column(name = "subtract_qty_from")
	public Boolean getSubtractQtyFrom() {
		return this.subtractQtyFrom;
	}

	public void setSubtractQtyFrom(Boolean subtractQtyFrom) {
		this.subtractQtyFrom = subtractQtyFrom;
	}

	@Column(name = "add_qty_to")
	public Boolean getAddQtyTo() {
		return this.addQtyTo;
	}

	public void setAddQtyTo(Boolean addQtyTo) {
		this.addQtyTo = addQtyTo;
	}

	@Column(name = "allowed_to_accesslevel")
	public String getAllowedToAccesslevel() {
		return this.allowedToAccesslevel;
	}

	public void setAllowedToAccesslevel(String allowedToAccesslevel) {
		this.allowedToAccesslevel = allowedToAccesslevel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stocknewTransactiontemplate")
	public Set<StocknewTransactions> getStocknewTransactionses() {
		return this.stocknewTransactionses;
	}

	public void setStocknewTransactionses(Set stocknewTransactionses) {
		this.stocknewTransactionses = stocknewTransactionses;
	}

}
