package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StocknewCategory generated by hbm2java
 */
@Entity
@Table(name = "stocknew_category")
public class StocknewCategory implements java.io.Serializable {

	private Integer id;
	private String name;
	private String allowedInTransactions;
	private Set stocknewItemses = new HashSet(0);

	public StocknewCategory() {
	}

	public StocknewCategory(String name, String allowedInTransactions, Set stocknewItemses) {
		this.name = name;
		this.allowedInTransactions = allowedInTransactions;
		this.stocknewItemses = stocknewItemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "allowed_in_transactions")
	public String getAllowedInTransactions() {
		return this.allowedInTransactions;
	}

	public void setAllowedInTransactions(String allowedInTransactions) {
		this.allowedInTransactions = allowedInTransactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stocknewCategory")
	public Set<StocknewItems> getStocknewItemses() {
		return this.stocknewItemses;
	}

	public void setStocknewItemses(Set stocknewItemses) {
		this.stocknewItemses = stocknewItemses;
	}

}
