package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StockContainerrowitemqty generated by hbm2java
 */
@Entity
@Table(name = "stock_containerrowitemqty")
public class StockContainerrowitemqty implements java.io.Serializable {

	private Integer id;
	private Branches branches;
	private StockContainers stockContainers;
	private StockItems stockItems;
	private StockRows stockRows;
	private String qty;

	public StockContainerrowitemqty() {
	}

	public StockContainerrowitemqty(Branches branches, StockContainers stockContainers, StockItems stockItems,
			StockRows stockRows, String qty) {
		this.branches = branches;
		this.stockContainers = stockContainers;
		this.stockItems = stockItems;
		this.stockRows = stockRows;
		this.qty = qty;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "container_id")
	public StockContainers getStockContainers() {
		return this.stockContainers;
	}

	public void setStockContainers(StockContainers stockContainers) {
		this.stockContainers = stockContainers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public StockItems getStockItems() {
		return this.stockItems;
	}

	public void setStockItems(StockItems stockItems) {
		this.stockItems = stockItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "row_id")
	public StockRows getStockRows() {
		return this.stockRows;
	}

	public void setStockRows(StockRows stockRows) {
		this.stockRows = stockRows;
	}

	@Column(name = "qty")
	public String getQty() {
		return this.qty;
	}

	public void setQty(String qty) {
		this.qty = qty;
	}

}
