package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TelecallerAccountHistory generated by hbm2java
 */
@Entity
@Table(name = "telecaller_account_history")
public class TelecallerAccountHistory implements java.io.Serializable {

	private Integer id;
	private Integer accountId;
	private Integer telecallerId;
	private Date fromDate;
	private Date finalToDate;

	public TelecallerAccountHistory() {
	}

	public TelecallerAccountHistory(Integer accountId, Integer telecallerId, Date fromDate, Date finalToDate) {
		this.accountId = accountId;
		this.telecallerId = telecallerId;
		this.fromDate = fromDate;
		this.finalToDate = finalToDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account_id")
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@Column(name = "telecaller_id")
	public Integer getTelecallerId() {
		return this.telecallerId;
	}

	public void setTelecallerId(Integer telecallerId) {
		this.telecallerId = telecallerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "from_date", length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "final_to_date", length = 19)
	public Date getFinalToDate() {
		return this.finalToDate;
	}

	public void setFinalToDate(Date finalToDate) {
		this.finalToDate = finalToDate;
	}

}
