package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestingUser generated by hbm2java
 */
@Entity
@Table(name = "testing_user")
public class TestingUser implements java.io.Serializable {

	private int id;
	private String name;
	private String role;

	public TestingUser() {
	}

	public TestingUser(int id) {
		this.id = id;
	}

	public TestingUser(int id, String name, String role) {
		this.id = id;
		this.name = name;
		this.role = role;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "role")
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
