package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name = "transactions")
public class Transactions implements java.io.Serializable {

	private Integer id;
	private Integer transactionTypeId;
	private Integer staffId;
	private Integer referenceId;
	private Integer branchId;
	private Integer voucherNoOriginal;
	private BigDecimal voucherNo;
	private String narration;
	private Date createdAt;
	private Date updatedAt;
	private Integer invoiceNo;
	private Byte isSaleInvoice;
	private Byte isInvoiceCancel;
	private Set agentTdses = new HashSet(0);

	public Transactions() {
	}

	public Transactions(Integer transactionTypeId, Integer staffId, Integer referenceId, Integer branchId,
			Integer voucherNoOriginal, BigDecimal voucherNo, String narration, Date createdAt, Date updatedAt,
			Integer invoiceNo, Byte isSaleInvoice, Byte isInvoiceCancel, Set agentTdses) {
		this.transactionTypeId = transactionTypeId;
		this.staffId = staffId;
		this.referenceId = referenceId;
		this.branchId = branchId;
		this.voucherNoOriginal = voucherNoOriginal;
		this.voucherNo = voucherNo;
		this.narration = narration;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.invoiceNo = invoiceNo;
		this.isSaleInvoice = isSaleInvoice;
		this.isInvoiceCancel = isInvoiceCancel;
		this.agentTdses = agentTdses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "transaction_type_id")
	public Integer getTransactionTypeId() {
		return this.transactionTypeId;
	}

	public void setTransactionTypeId(Integer transactionTypeId) {
		this.transactionTypeId = transactionTypeId;
	}

	@Column(name = "staff_id")
	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	@Column(name = "reference_id")
	public Integer getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(Integer referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "branch_id")
	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	@Column(name = "voucher_no_original")
	public Integer getVoucherNoOriginal() {
		return this.voucherNoOriginal;
	}

	public void setVoucherNoOriginal(Integer voucherNoOriginal) {
		this.voucherNoOriginal = voucherNoOriginal;
	}

	@Column(name = "voucher_no", precision = 11, scale = 3)
	public BigDecimal getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(BigDecimal voucherNo) {
		this.voucherNo = voucherNo;
	}

	@Column(name = "Narration", length = 65535)
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "invoice_no")
	public Integer getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(Integer invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "is_sale_invoice")
	public Byte getIsSaleInvoice() {
		return this.isSaleInvoice;
	}

	public void setIsSaleInvoice(Byte isSaleInvoice) {
		this.isSaleInvoice = isSaleInvoice;
	}

	@Column(name = "is_invoice_cancel")
	public Byte getIsInvoiceCancel() {
		return this.isInvoiceCancel;
	}

	public void setIsInvoiceCancel(Byte isInvoiceCancel) {
		this.isInvoiceCancel = isInvoiceCancel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactions")
	public Set<AgentTds> getAgentTdses() {
		return this.agentTdses;
	}

	public void setAgentTdses(Set agentTdses) {
		this.agentTdses = agentTdses;
	}

}
