package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransactionTypes generated by hbm2java
 */
@Entity
@Table(name = "transaction_types")
public class TransactionTypes implements java.io.Serializable {

	private Integer id;
	private String name;
	private String fromAc;
	private String toAc;
	private String defaultNarration;

	public TransactionTypes() {
	}

	public TransactionTypes(String defaultNarration) {
		this.defaultNarration = defaultNarration;
	}

	public TransactionTypes(String name, String fromAc, String toAc, String defaultNarration) {
		this.name = name;
		this.fromAc = fromAc;
		this.toAc = toAc;
		this.defaultNarration = defaultNarration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "FromAC", length = 45)
	public String getFromAc() {
		return this.fromAc;
	}

	public void setFromAc(String fromAc) {
		this.fromAc = fromAc;
	}

	@Column(name = "ToAC", length = 45)
	public String getToAc() {
		return this.toAc;
	}

	public void setToAc(String toAc) {
		this.toAc = toAc;
	}

	@Column(name = "Default_Narration", nullable = false)
	public String getDefaultNarration() {
		return this.defaultNarration;
	}

	public void setDefaultNarration(String defaultNarration) {
		this.defaultNarration = defaultNarration;
	}

}
