package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionRow generated by hbm2java
 */
@Entity
@Table(name = "transaction_row")
public class TransactionRow implements java.io.Serializable {

	private Integer id;
	private Integer accountId;
	private int transactionTypeId;
	private int staffId;
	private Long voucherNo;
	private String narration;
	private BigDecimal amountDr;
	private BigDecimal amountCr;
	private Date createdAt;
	private Date updatedAt;
	private int branchId;
	private Integer referenceAccountId;
	private Long displayVoucherNo;
	private String side;
	private int accountsInSide;
	private Integer transactionId;
	private int schemeId;
	private int balanceSheetId;

	public TransactionRow() {
	}

	public TransactionRow(int transactionTypeId, int staffId, int branchId, String side, int accountsInSide,
			int schemeId, int balanceSheetId) {
		this.transactionTypeId = transactionTypeId;
		this.staffId = staffId;
		this.branchId = branchId;
		this.side = side;
		this.accountsInSide = accountsInSide;
		this.schemeId = schemeId;
		this.balanceSheetId = balanceSheetId;
	}

	public TransactionRow(Integer accountId, int transactionTypeId, int staffId, Long voucherNo, String narration,
			BigDecimal amountDr, BigDecimal amountCr, Date createdAt, Date updatedAt, int branchId,
			Integer referenceAccountId, Long displayVoucherNo, String side, int accountsInSide, Integer transactionId,
			int schemeId, int balanceSheetId) {
		this.accountId = accountId;
		this.transactionTypeId = transactionTypeId;
		this.staffId = staffId;
		this.voucherNo = voucherNo;
		this.narration = narration;
		this.amountDr = amountDr;
		this.amountCr = amountCr;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.branchId = branchId;
		this.referenceAccountId = referenceAccountId;
		this.displayVoucherNo = displayVoucherNo;
		this.side = side;
		this.accountsInSide = accountsInSide;
		this.transactionId = transactionId;
		this.schemeId = schemeId;
		this.balanceSheetId = balanceSheetId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account_id")
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@Column(name = "transaction_type_id", nullable = false)
	public int getTransactionTypeId() {
		return this.transactionTypeId;
	}

	public void setTransactionTypeId(int transactionTypeId) {
		this.transactionTypeId = transactionTypeId;
	}

	@Column(name = "staff_id", nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@Column(name = "voucher_no")
	public Long getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(Long voucherNo) {
		this.voucherNo = voucherNo;
	}

	@Column(name = "Narration", length = 65535)
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	@Column(name = "amountDr", precision = 20, scale = 3)
	public BigDecimal getAmountDr() {
		return this.amountDr;
	}

	public void setAmountDr(BigDecimal amountDr) {
		this.amountDr = amountDr;
	}

	@Column(name = "amountCr", precision = 20, scale = 3)
	public BigDecimal getAmountCr() {
		return this.amountCr;
	}

	public void setAmountCr(BigDecimal amountCr) {
		this.amountCr = amountCr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "branch_id", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	@Column(name = "reference_account_id")
	public Integer getReferenceAccountId() {
		return this.referenceAccountId;
	}

	public void setReferenceAccountId(Integer referenceAccountId) {
		this.referenceAccountId = referenceAccountId;
	}

	@Column(name = "display_voucher_no")
	public Long getDisplayVoucherNo() {
		return this.displayVoucherNo;
	}

	public void setDisplayVoucherNo(Long displayVoucherNo) {
		this.displayVoucherNo = displayVoucherNo;
	}

	@Column(name = "side", nullable = false, length = 2)
	public String getSide() {
		return this.side;
	}

	public void setSide(String side) {
		this.side = side;
	}

	@Column(name = "accounts_in_side", nullable = false)
	public int getAccountsInSide() {
		return this.accountsInSide;
	}

	public void setAccountsInSide(int accountsInSide) {
		this.accountsInSide = accountsInSide;
	}

	@Column(name = "transaction_id")
	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "scheme_id", nullable = false)
	public int getSchemeId() {
		return this.schemeId;
	}

	public void setSchemeId(int schemeId) {
		this.schemeId = schemeId;
	}

	@Column(name = "balance_sheet_id", nullable = false)
	public int getBalanceSheetId() {
		return this.balanceSheetId;
	}

	public void setBalanceSheetId(int balanceSheetId) {
		this.balanceSheetId = balanceSheetId;
	}

}
