package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * XbankEmployees generated by hbm2java
 */
@Entity
@Table(name = "xbank_employees")
public class XbankEmployees implements java.io.Serializable {

	private Integer id;
	private Branches branches;
	private String name;
	private String designation;
	private String department;
	private Date dob;
	private String experince;
	private String prevCompany;
	private String prevDepartment;
	private Date prevLeavingCompanyDate;
	private String leavingResion;
	private String fatherName;
	private String motherName;
	private String maritalStatus;
	private String contactNo;
	private String emailId;
	private String permanentAddress;
	private String presentAddress;
	private Date dateOfJoining;
	private Date dateOfLeaving;
	private String pfNo;
	private String pfNominee;
	private String esiNo;
	private String esiNominee;
	private String panNo;
	private String drivingLicenceNo;
	private String validityOfDrivingLicence;
	private String bankName;
	private String bankAccountNo;
	private String paymemtMode;
	private String pfDeduct;
	private String employeeStatus;
	private String basicSalary;
	private String otherAllowance;
	private String societyContri;
	private String netPayable;
	private String netSalary;
	private String empCode;
	private String relationWithNominee;
	private String lastQualification;
	private String pfJoiningDate;
	private String agreementDate;
	private Boolean isActive;
	private Integer employeeImagePhoto;
	private Integer employeeImageSignature;
	private String emergencyNo;
	private String openingCl;
	private Date effectiveClDate;
	private Integer employeeImagePhotoId;
	private Integer employeeImageSignatureId;
	private Set employeeSalaryRecords = new HashSet(0);

	public XbankEmployees() {
	}

	public XbankEmployees(Branches branches, String name, String designation, String department, Date dob,
			String experince, String prevCompany, String prevDepartment, Date prevLeavingCompanyDate,
			String leavingResion, String fatherName, String motherName, String maritalStatus, String contactNo,
			String emailId, String permanentAddress, String presentAddress, Date dateOfJoining, Date dateOfLeaving,
			String pfNo, String pfNominee, String esiNo, String esiNominee, String panNo, String drivingLicenceNo,
			String validityOfDrivingLicence, String bankName, String bankAccountNo, String paymemtMode, String pfDeduct,
			String employeeStatus, String basicSalary, String otherAllowance, String societyContri, String netPayable,
			String netSalary, String empCode, String relationWithNominee, String lastQualification,
			String pfJoiningDate, String agreementDate, Boolean isActive, Integer employeeImagePhoto,
			Integer employeeImageSignature, String emergencyNo, String openingCl, Date effectiveClDate,
			Integer employeeImagePhotoId, Integer employeeImageSignatureId, Set employeeSalaryRecords) {
		this.branches = branches;
		this.name = name;
		this.designation = designation;
		this.department = department;
		this.dob = dob;
		this.experince = experince;
		this.prevCompany = prevCompany;
		this.prevDepartment = prevDepartment;
		this.prevLeavingCompanyDate = prevLeavingCompanyDate;
		this.leavingResion = leavingResion;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.maritalStatus = maritalStatus;
		this.contactNo = contactNo;
		this.emailId = emailId;
		this.permanentAddress = permanentAddress;
		this.presentAddress = presentAddress;
		this.dateOfJoining = dateOfJoining;
		this.dateOfLeaving = dateOfLeaving;
		this.pfNo = pfNo;
		this.pfNominee = pfNominee;
		this.esiNo = esiNo;
		this.esiNominee = esiNominee;
		this.panNo = panNo;
		this.drivingLicenceNo = drivingLicenceNo;
		this.validityOfDrivingLicence = validityOfDrivingLicence;
		this.bankName = bankName;
		this.bankAccountNo = bankAccountNo;
		this.paymemtMode = paymemtMode;
		this.pfDeduct = pfDeduct;
		this.employeeStatus = employeeStatus;
		this.basicSalary = basicSalary;
		this.otherAllowance = otherAllowance;
		this.societyContri = societyContri;
		this.netPayable = netPayable;
		this.netSalary = netSalary;
		this.empCode = empCode;
		this.relationWithNominee = relationWithNominee;
		this.lastQualification = lastQualification;
		this.pfJoiningDate = pfJoiningDate;
		this.agreementDate = agreementDate;
		this.isActive = isActive;
		this.employeeImagePhoto = employeeImagePhoto;
		this.employeeImageSignature = employeeImageSignature;
		this.emergencyNo = emergencyNo;
		this.openingCl = openingCl;
		this.effectiveClDate = effectiveClDate;
		this.employeeImagePhotoId = employeeImagePhotoId;
		this.employeeImageSignatureId = employeeImageSignatureId;
		this.employeeSalaryRecords = employeeSalaryRecords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "designation")
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "department")
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "experince")
	public String getExperince() {
		return this.experince;
	}

	public void setExperince(String experince) {
		this.experince = experince;
	}

	@Column(name = "prev_company")
	public String getPrevCompany() {
		return this.prevCompany;
	}

	public void setPrevCompany(String prevCompany) {
		this.prevCompany = prevCompany;
	}

	@Column(name = "prev_department")
	public String getPrevDepartment() {
		return this.prevDepartment;
	}

	public void setPrevDepartment(String prevDepartment) {
		this.prevDepartment = prevDepartment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "prev_leaving_company_date", length = 10)
	public Date getPrevLeavingCompanyDate() {
		return this.prevLeavingCompanyDate;
	}

	public void setPrevLeavingCompanyDate(Date prevLeavingCompanyDate) {
		this.prevLeavingCompanyDate = prevLeavingCompanyDate;
	}

	@Column(name = "leaving_resion")
	public String getLeavingResion() {
		return this.leavingResion;
	}

	public void setLeavingResion(String leavingResion) {
		this.leavingResion = leavingResion;
	}

	@Column(name = "father_name")
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "mother_name")
	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	@Column(name = "marital_status")
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "contact_no")
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "email_id")
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "permanent_address")
	public String getPermanentAddress() {
		return this.permanentAddress;
	}

	public void setPermanentAddress(String permanentAddress) {
		this.permanentAddress = permanentAddress;
	}

	@Column(name = "present_address")
	public String getPresentAddress() {
		return this.presentAddress;
	}

	public void setPresentAddress(String presentAddress) {
		this.presentAddress = presentAddress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_joining", length = 10)
	public Date getDateOfJoining() {
		return this.dateOfJoining;
	}

	public void setDateOfJoining(Date dateOfJoining) {
		this.dateOfJoining = dateOfJoining;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_leaving", length = 10)
	public Date getDateOfLeaving() {
		return this.dateOfLeaving;
	}

	public void setDateOfLeaving(Date dateOfLeaving) {
		this.dateOfLeaving = dateOfLeaving;
	}

	@Column(name = "pf_no")
	public String getPfNo() {
		return this.pfNo;
	}

	public void setPfNo(String pfNo) {
		this.pfNo = pfNo;
	}

	@Column(name = "pf_nominee")
	public String getPfNominee() {
		return this.pfNominee;
	}

	public void setPfNominee(String pfNominee) {
		this.pfNominee = pfNominee;
	}

	@Column(name = "esi_no")
	public String getEsiNo() {
		return this.esiNo;
	}

	public void setEsiNo(String esiNo) {
		this.esiNo = esiNo;
	}

	@Column(name = "esi_nominee")
	public String getEsiNominee() {
		return this.esiNominee;
	}

	public void setEsiNominee(String esiNominee) {
		this.esiNominee = esiNominee;
	}

	@Column(name = "pan_no")
	public String getPanNo() {
		return this.panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	@Column(name = "driving_licence_no")
	public String getDrivingLicenceNo() {
		return this.drivingLicenceNo;
	}

	public void setDrivingLicenceNo(String drivingLicenceNo) {
		this.drivingLicenceNo = drivingLicenceNo;
	}

	@Column(name = "validity_of_driving_licence")
	public String getValidityOfDrivingLicence() {
		return this.validityOfDrivingLicence;
	}

	public void setValidityOfDrivingLicence(String validityOfDrivingLicence) {
		this.validityOfDrivingLicence = validityOfDrivingLicence;
	}

	@Column(name = "bank_name")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_account_no")
	public String getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(String bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}

	@Column(name = "paymemt_mode")
	public String getPaymemtMode() {
		return this.paymemtMode;
	}

	public void setPaymemtMode(String paymemtMode) {
		this.paymemtMode = paymemtMode;
	}

	@Column(name = "pf_deduct")
	public String getPfDeduct() {
		return this.pfDeduct;
	}

	public void setPfDeduct(String pfDeduct) {
		this.pfDeduct = pfDeduct;
	}

	@Column(name = "employee_status")
	public String getEmployeeStatus() {
		return this.employeeStatus;
	}

	public void setEmployeeStatus(String employeeStatus) {
		this.employeeStatus = employeeStatus;
	}

	@Column(name = "basic_salary")
	public String getBasicSalary() {
		return this.basicSalary;
	}

	public void setBasicSalary(String basicSalary) {
		this.basicSalary = basicSalary;
	}

	@Column(name = "other_allowance")
	public String getOtherAllowance() {
		return this.otherAllowance;
	}

	public void setOtherAllowance(String otherAllowance) {
		this.otherAllowance = otherAllowance;
	}

	@Column(name = "society_contri")
	public String getSocietyContri() {
		return this.societyContri;
	}

	public void setSocietyContri(String societyContri) {
		this.societyContri = societyContri;
	}

	@Column(name = "net_payable")
	public String getNetPayable() {
		return this.netPayable;
	}

	public void setNetPayable(String netPayable) {
		this.netPayable = netPayable;
	}

	@Column(name = "net_salary")
	public String getNetSalary() {
		return this.netSalary;
	}

	public void setNetSalary(String netSalary) {
		this.netSalary = netSalary;
	}

	@Column(name = "emp_code")
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Column(name = "relation_with_nominee")
	public String getRelationWithNominee() {
		return this.relationWithNominee;
	}

	public void setRelationWithNominee(String relationWithNominee) {
		this.relationWithNominee = relationWithNominee;
	}

	@Column(name = "last_qualification")
	public String getLastQualification() {
		return this.lastQualification;
	}

	public void setLastQualification(String lastQualification) {
		this.lastQualification = lastQualification;
	}

	@Column(name = "pf_joining_date")
	public String getPfJoiningDate() {
		return this.pfJoiningDate;
	}

	public void setPfJoiningDate(String pfJoiningDate) {
		this.pfJoiningDate = pfJoiningDate;
	}

	@Column(name = "agreement_date")
	public String getAgreementDate() {
		return this.agreementDate;
	}

	public void setAgreementDate(String agreementDate) {
		this.agreementDate = agreementDate;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "employee_image_photo")
	public Integer getEmployeeImagePhoto() {
		return this.employeeImagePhoto;
	}

	public void setEmployeeImagePhoto(Integer employeeImagePhoto) {
		this.employeeImagePhoto = employeeImagePhoto;
	}

	@Column(name = "employee_image_signature")
	public Integer getEmployeeImageSignature() {
		return this.employeeImageSignature;
	}

	public void setEmployeeImageSignature(Integer employeeImageSignature) {
		this.employeeImageSignature = employeeImageSignature;
	}

	@Column(name = "emergency_no")
	public String getEmergencyNo() {
		return this.emergencyNo;
	}

	public void setEmergencyNo(String emergencyNo) {
		this.emergencyNo = emergencyNo;
	}

	@Column(name = "opening_cl")
	public String getOpeningCl() {
		return this.openingCl;
	}

	public void setOpeningCl(String openingCl) {
		this.openingCl = openingCl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_cl_date", length = 10)
	public Date getEffectiveClDate() {
		return this.effectiveClDate;
	}

	public void setEffectiveClDate(Date effectiveClDate) {
		this.effectiveClDate = effectiveClDate;
	}

	@Column(name = "employee_image_photo_id")
	public Integer getEmployeeImagePhotoId() {
		return this.employeeImagePhotoId;
	}

	public void setEmployeeImagePhotoId(Integer employeeImagePhotoId) {
		this.employeeImagePhotoId = employeeImagePhotoId;
	}

	@Column(name = "employee_image_signature_id")
	public Integer getEmployeeImageSignatureId() {
		return this.employeeImageSignatureId;
	}

	public void setEmployeeImageSignatureId(Integer employeeImageSignatureId) {
		this.employeeImageSignatureId = employeeImageSignatureId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "xbankEmployees")
	public Set<EmployeeSalaryRecord> getEmployeeSalaryRecords() {
		return this.employeeSalaryRecords;
	}

	public void setEmployeeSalaryRecords(Set employeeSalaryRecords) {
		this.employeeSalaryRecords = employeeSalaryRecords;
	}

}
