package com.service.banking.hibernateEntity;
// Generated Feb 20, 2020 6:19:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Xlog generated by hbm2java
 */
@Entity
@Table(name = "xLog")
public class Xlog implements java.io.Serializable {

	private Integer id;
	private Integer staffId;
	private String modelClass;
	private Integer pkId;
	private Date createdAt;
	private String name;
	private String type;

	public Xlog() {
	}

	public Xlog(Integer staffId, String modelClass, Integer pkId, Date createdAt, String name, String type) {
		this.staffId = staffId;
		this.modelClass = modelClass;
		this.pkId = pkId;
		this.createdAt = createdAt;
		this.name = name;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "staff_id")
	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	@Column(name = "model_class")
	public String getModelClass() {
		return this.modelClass;
	}

	public void setModelClass(String modelClass) {
		this.modelClass = modelClass;
	}

	@Column(name = "pk_id")
	public Integer getPkId() {
		return this.pkId;
	}

	public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
